export const arrayOfCities = [
  "A Coruña",
  "Aachen",
  "Aarhus",
  "Abbeville",
  "Aberdeen",
  "Abidjan",
  "Abilene",
  "Abu Dhabi",
  "Abuja",
  "Acapulco",
  "Accra",
  "Adamstown",
  "Addis Ababa",
  "Adelaide",
  "Adelboden",
  "Agadir",
  "Agde",
  "Agen",
  "Agios Nikolaos",
  "Agra",
  "Agrigento",
  "Agropoli",
  "Ahmedabad",
  "Aigues-Mortes",
  "Aix-en-Provence",
  "Aix-les-Bains",
  "Ajaccio",
  "Ajman",
  "Akron",
  "Al Ain",
  "Alameda",
  "Alanya",
  "Alaró",
  "Albacete",
  "Albany",
  "Albenga",
  "Albi",
  "Albufeira",
  "Albuquerque",
  "Alcudia",
  "Aleppo",
  "Alessandria",
  "Ålesund",
  "Alexandria",
  "Algeciras",
  "Alghero",
  "Algiers",
  "Alicante",
  "Alkmaar",
  "Allentown",
  "Almaty",
  "Alofi",
  "Alpe d'Huez",
  "Alta Badia",
  "Altea",
  "Altoona",
  "Amagansett",
  "Amalfi",
  "Amapala",
  "Amarillo",
  "Ambon",
  "Amersfoort",
  "Amiens",
  "Amman",
  "Amsterdam",
  "Anaheim",
  "Anchorage",
  "Ancona",
  "Andalo",
  "Andermatt",
  "Andorra la Vella",
  "Andratx",
  "Andria",
  "Angeles City",
  "Angers",
  "Angoulême",
  "Ankara",
  "Ann Arbor",
  "Anna Maria City",
  "Annapolis",
  "Annecy",
  "Antalya",
  "Antananarivo",
  "Antibes",
  "Antigua Guatemala",
  "Antwerp",
  "Anzio",
  "Ao Nang",
  "Aosta",
  "Apeldoorn",
  "Apia",
  "Appleton",
  "Aqaba",
  "Aracaju",
  "Arcachon",
  "Arenzano",
  "Arequipa",
  "Arezzo",
  "Argostoli",
  "Arica",
  "Arles",
  "Arlington",
  "Armagh",
  "Arnhem",
  "Arosa",
  "Arras",
  "Arrecife",
  "Artà",
  "Asbury Park",
  "Ascoli Piceno",
  "Ascona",
  "Ashdod",
  "Ashgabat",
  "Ashkelon",
  "Asmara",
  "Aspen",
  "Asti",
  "Astoria",
  "Asunción",
  "Atafu",
  "Athens",
  "Athlone",
  "Atlanta",
  "Atlantic Beach",
  "Atlantic City",
  "Atuona",
  "Auckland",
  "Augsburg",
  "Augusta",
  "Aurora",
  "Austin",
  "Auxerre",
  "Avalon",
  "Avarua",
  "Avatoru",
  "Aveiro",
  "Avellino",
  "Avignon",
  "Avila Beach",
  "Avon",
  "Avoriaz",
  "Axamer Lizum",
  "Ayia Napa",
  "Azusa",
  "Bad Gastein",
  "Bad Hofgastein",
  "Baden",
  "Baghdad",
  "Baiona",
  "Bakersfield",
  "Baku",
  "Bald Head Island",
  "Baltimore",
  "Bamako",
  "Banda Aceh",
  "Bandar Seri Begawan",
  "Bandol",
  "Banff",
  "Bangalore",
  "Bangkok",
  "Bangor",
  "Bangui",
  "Banjul",
  "Bar",
  "Bar Harbor",
  "Barcelona",
  "Bari",
  "Barletta",
  "Barnegat Light",
  "Barnum Island",
  "Barrie",
  "Barstow",
  "Basel",
  "Basey",
  "Basseterre",
  "Basse-Terre",
  "Bastia",
  "Bata",
  "Batam",
  "Bath",
  "Baton Rouge",
  "Batu",
  "Batumi",
  "Bayonne",
  "Beach Haven",
  "Bear Island",
  "Beaufort",
  "Beaulieu-sur-Mer",
  "Beaumont",
  "Beaune",
  "Beersheba",
  "Beijing",
  "Beirut",
  "Belek",
  "Belfast",
  "Belfort",
  "Belgrade",
  "Belize City",
  "Bellingham",
  "Bellinzona",
  "Belluno",
  "Belmopan",
  "Belo Horizonte",
  "Bemidji",
  "Benalmadena",
  "Bend",
  "Bendigo",
  "Benevento",
  "Benicàssim",
  "Benidorm",
  "Bergamo",
  "Bergen",
  "Bergerac",
  "Berkeley",
  "Berlin",
  "Bern",
  "Besançon",
  "Bethlehem",
  "Beverly Hills",
  "Béziers",
  "Biarritz",
  "Biel/Bienne",
  "Bielefeld",
  "Biella",
  "Big Bear Lake",
  "Big Pine Key",
  "Big Sur",
  "Bilbao",
  "Billings",
  "Biloxi",
  "Birmingham",
  "Bishkek",
  "Bismarck",
  "Bissau",
  "Blanes",
  "Bled",
  "Blois",
  "Bloomington",
  "Blumenau",
  "Boca Chica",
  "Boca Grande",
  "Boca Raton",
  "Bochum",
  "Bodrum",
  "Bogotá",
  "Boise",
  "Bologna",
  "Bolzano",
  "Bonifacio",
  "Bonn",
  "Bordeaux",
  "Bordighera",
  "Bormio",
  "Boston",
  "Boulder",
  "Boulogne-sur-Mer",
  "Bourges",
  "Bowling Green",
  "Boynton Beach",
  "Bozeman",
  "Bradenton",
  "Bradenton Beach",
  "Bradford",
  "Braga",
  "Brampton",
  "Brandon",
  "Brantford",
  "Brasilia",
  "Bratislava",
  "Braunschweig",
  "Brazzaville",
  "Breda",
  "Bregenz",
  "Brela",
  "Bremen",
  "Bremerhaven",
  "Brescia",
  "Brest",
  "Briançon",
  "Bridgehampton",
  "Bridgeport",
  "Bridgetown",
  "Brigantine",
  "Brighton",
  "Brindisi",
  "Brisbane",
  "Bristol",
  "Brixen",
  "Brixental",
  "Brno",
  "Brookings",
  "Brownsville",
  "Bruges",
  "Brunswick",
  "Brussels",
  "Bucharest",
  "Budapest",
  "Budva",
  "Buenos Aires",
  "Buffalo",
  "Bujumbura",
  "Bukittinggi",
  "Burgas",
  "Burlington",
  "Burnt Pine",
  "Burton",
  "Butte",
  "Buxton",
  "Cabo San Lucas",
  "Cadaqués",
  "Cádiz",
  "Caen",
  "Cagliari",
  "Cagnes-sur-Mer",
  "Cairns",
  "Cairo",
  "Cala Bona",
  "Cala d'Or",
  "Cala Millor",
  "Cala Ratjada",
  "Calais",
  "Calella",
  "Calgary",
  "Cali",
  "Caloundra",
  "Calp",
  "Caltanissetta",
  "Calvi",
  "Cambridge",
  "Cambrils",
  "Camden",
  "Campbell River",
  "Campinas",
  "Campobasso",
  "Can Pastilla",
  "Can Picafort",
  "Canazei",
  "Canberra",
  "Cancun",
  "Cannes",
  "Cannon Beach",
  "Canterbury",
  "Canton",
  "Canyamel",
  "Capdepera",
  "Cape Canaveral",
  "Cape Coral",
  "Cape May",
  "Cape Town",
  "Capitola",
  "Captiva",
  "Caracas",
  "Carbonia",
  "Carcassonne",
  "Cardiff",
  "Carlisle",
  "Carlsbad",
  "Carmel-by-the-Sea",
  "Carolina Beach",
  "Carova Beach",
  "Carpi",
  "Carpinteria",
  "Carrara",
  "Carson City",
  "Cartagena",
  "Casablanca",
  "Caserta",
  "Casper",
  "Cassis",
  "Castellón de la Plana",
  "Castelrotto",
  "Castletown",
  "Castries",
  "Caswell Beach",
  "Catania",
  "Catanzaro",
  "Caxias do Sul",
  "Cayenne",
  "Cebu City",
  "Cedar Island",
  "Cedar Key",
  "Cedar Rapids",
  "Celle",
  "Cervinia",
  "Cesena",
  "Český Krumlov",
  "Çeşme",
  "Chamonix",
  "Chandler",
  "Chania",
  "Charleroi",
  "Charleston",
  "Charlestown",
  "Charlotte",
  "Charlotte Amalie",
  "Charlottetown",
  "Chartres",
  "Chatham",
  "Chattanooga",
  "Chelmsford",
  "Chemnitz",
  "Chennai",
  "Cherbourg",
  "Chesapeake",
  "Chester",
  "Cheyenne",
  "Chiang Mai",
  "Chiang Rai",
  "Chiavari",
  "Chicago",
  "Chichester",
  "Chiclayo",
  "Chieti",
  "Chincoteague",
  "Chioggia",
  "Chios",
  "Chișinău",
  "Chokoloskee",
  "Chonburi",
  "Christchurch",
  "Christiansted",
  "Chula Vista",
  "Chur",
  "Cincinnati",
  "Ciutadella de Menorca",
  "Civitavecchia",
  "Clarksville",
  "Clearwater",
  "Clearwater Beach",
  "Clermont-Ferrand",
  "Cleveland",
  "Cockburn Town",
  "Cocoa Beach",
  "Coconut Creek",
  "Coimbra",
  "Collioure",
  "Colmar",
  "Cologne",
  "Colombo",
  "Colón",
  "Colonia del Sacramento",
  "Colorado Springs",
  "Columbia",
  "Columbus",
  "Como",
  "Conakry",
  "Concepción",
  "Concord",
  "Conil de la Frontera",
  "Conway",
  "Copenhagen",
  "Coral Springs",
  "Córdoba",
  "Corfu",
  "Corinth",
  "Cork",
  "Coro",
  "Corolla",
  "Coron Town",
  "Coronado",
  "Corpus Christi",
  "Corralejo",
  "Cortina d'Ampezzo",
  "Cosenza",
  "Costa Adeje",
  "Cotabato City",
  "Cottbus",
  "Courchevel",
  "Courmayeur",
  "Courtenay",
  "Coventry",
  "Covington",
  "Coxen Hole",
  "Coyhaique",
  "Cozumel",
  "Crans-Montana",
  "Cremona",
  "Crotone",
  "Cruz Bay",
  "Cudjoe Key",
  "Cuenca",
  "Cumaná",
  "Cuneo",
  "Cusco",
  "Da Nang",
  "Dachau",
  "Dahab",
  "Dakar",
  "Dallas",
  "Damascus",
  "Dana Point",
  "Dar es Salaam",
  "Darien",
  "Darmstadt",
  "Darwin",
  "Daufuskie Island",
  "Daugavpils",
  "Dauphin Island",
  "Davao City",
  "Davenport",
  "Davos",
  "Dayton",
  "Daytona Beach",
  "Deauville",
  "Decatur",
  "Deerfield Beach",
  "Del Mar",
  "Delft",
  "Delhi",
  "Delray Beach",
  "Den Bosch",
  "Denia",
  "Denpasar",
  "Denton",
  "Denver",
  "Derby",
  "Derry",
  "Des Moines",
  "Destin",
  "Detroit",
  "Dewees Island",
  "Dhaka",
  "Diamond Beach",
  "Didim",
  "Dieppe",
  "Dijon",
  "Dili",
  "Djibouti",
  "Dodoma",
  "Doha",
  "Dolomiti Superski",
  "Dordrecht",
  "Dorfgastein",
  "Dortmund",
  "Dothan",
  "Douala",
  "Douglas",
  "Dover",
  "Dresden",
  "Dubai",
  "Dublin",
  "Dubrovnik",
  "Duck",
  "Duisburg",
  "Duluth",
  "Dumaguete",
  "Dumai",
  "Duncan",
  "Dundalk",
  "Dundee",
  "Dunedin",
  "Dunkirk",
  "Durham",
  "Dushanbe",
  "Düsseldorf",
  "Dzaoudzi",
  "East Atlantic Beach",
  "East Hampton",
  "Eastbourne",
  "Eastport",
  "Eatons Neck",
  "Eau Claire",
  "Edgartown",
  "Edinburgh",
  "Edisto Beach",
  "Edmonton",
  "Eilat",
  "Eindhoven",
  "El Nido",
  "El Paso",
  "Elche",
  "Elizabeth",
  "Elko",
  "Ellmau",
  "Elm",
  "Emerald Isle",
  "Empuriabrava",
  "Encinitas",
  "Engelberg",
  "Englewood Beach",
  "Enna",
  "Enschede",
  "Épinal",
  "Erfurt",
  "Erie",
  "Erlangen",
  "Esbjerg",
  "Espace Killy",
  "Essaouira",
  "Essen",
  "Estepona",
  "Étretat",
  "Eugene",
  "Eureka",
  "Evansville",
  "Everett",
  "Everglades City",
  "Exeter",
  "Èze",
  "Faenza",
  "Fairbanks",
  "Fakaofo",
  "Falmouth",
  "Famagusta",
  "Fano",
  "Fargo",
  "Faro",
  "Fayetteville",
  "Fermo",
  "Fernandina Beach",
  "Ferrara",
  "Fethiye",
  "Fez",
  "Fieberbrunn",
  "Figure Eight Island",
  "Filzmoos",
  "Finale Ligure",
  "Fisher Island",
  "Fiumicino",
  "Flagstaff",
  "Flaine",
  "Flint",
  "Florence",
  "Flores",
  "Foggia",
  "Folgarida",
  "Folly Beach",
  "Fontana",
  "Forest Beach",
  "Forlì",
  "Fort Bragg",
  "Fort Caswell",
  "Fort Collins",
  "Fort Fremont",
  "Fort Lauderdale",
  "Fort Myers",
  "Fort Myers Beach",
  "Fort Pierce",
  "Fort Smith",
  "Fort Walton Beach",
  "Fort Wayne",
  "Fort Worth",
  "Fort-de-France",
  "Forte dei Marmi",
  "Foz do Iguaçu",
  "Frankfort",
  "Frankfurt am Main",
  "Franklin",
  "Frederick",
  "Fredericton",
  "Frederiksted",
  "Freeport",
  "Freetown",
  "Freiburg",
  "Fremont",
  "Fresno",
  "Fribourg",
  "Fripp Island",
  "Frisco",
  "Frogmore",
  "Frosinone",
  "Fuengirola",
  "Fujairah",
  "Fukuoka",
  "Funafuti",
  "Funchal",
  "Gaborone",
  "Gainesville",
  "Galtür",
  "Galway",
  "Gandia",
  "Garden Grove",
  "Garland",
  "Garumaoa",
  "Gastonia",
  "Gatineau",
  "Gaza City",
  "Gdansk",
  "Gdynia",
  "Geelong",
  "Gelsenkirchen",
  "Geneva",
  "Genoa",
  "George Town",
  "Georgetown",
  "Ghent",
  "Gijón",
  "Gilbert",
  "Girona",
  "Gitega",
  "Giza",
  "Glasgow",
  "Glendale",
  "Gloucester",
  "Gold Coast",
  "Goleta",
  "Gorizia",
  "Gosau",
  "Gothenburg",
  "Göttingen",
  "Gouda",
  "Granada",
  "Grand Forks",
  "Grand Island",
  "Grand Junction",
  "Grand Prairie",
  "Grand Rapids",
  "Grande Prairie",
  "Granville",
  "Grasse",
  "Graz",
  "Great Falls",
  "Greeley",
  "Green Bay",
  "Greensboro",
  "Greenville NC",
  "Greenville SC",
  "Grenoble",
  "Grindelwald",
  "Groningen",
  "Grossarl",
  "Grosseto",
  "Grover Beach",
  "Gstaad",
  "Guadalajara",
  "Guadalupe",
  "Guangzhou",
  "Guatemala City",
  "Guayaquil",
  "Guelph",
  "Guimarães",
  "Gulf Shores",
  "Gulfport",
  "Gustavia",
  "Haarlem",
  "Haifa",
  "Hakahau",
  "Half Moon Bay",
  "Halifax",
  "Halle",
  "Hamburg",
  "Hamilton",
  "Hampton",
  "Hampton Bays",
  "Hanford",
  "Hangzhou",
  "Hannover",
  "Hanoi",
  "Harare",
  "Harbor Island",
  "Harbor Isle",
  "Harbour Town",
  "Hargeisa",
  "Harkers Island",
  "Harrisburg",
  "Hartford",
  "Harvey Cedars",
  "Hasselt",
  "Hastings",
  "Hat Yai",
  "Hatteras",
  "Hattiesburg",
  "Havana",
  "Healdsburg",
  "Heidelberg",
  "Heilbronn",
  "Heiligenblut",
  "Helena",
  "Helsinki",
  "Henderson",
  "Heraklion",
  "Herceg Novi",
  "Hereford",
  "Hermosa Beach",
  "Hervey Bay",
  "Hialeah",
  "Hillsboro",
  "Hilton Head Island",
  "Hilton Head Plantation",
  "Hinterglemm",
  "Hinterstoder",
  "Hiroshima",
  "Hitianau",
  "Hoi An",
  "Hobart",
  "Ho Chi Minh City",
  "Holbrook",
  "Holden Beach",
  "Hollywood",
  "Holmes Beach",
  "Honfleur",
  "Hong Kong",
  "Honiara",
  "Honolulu",
  "Horsens",
  "Hot Springs",
  "Houston",
  "Hua Hin",
  "Hue",
  "Hunting Island",
  "Huntington",
  "Huntington Beach",
  "Huntsville",
  "Hurghada",
  "Hvar",
  "Hyères",
  "Ibiza Town",
  "Iloilo City",
  "Imola",
  "Imperia",
  "Inca",
  "Indian Beach",
  "Indianapolis",
  "Ingolstadt",
  "Innsbruck",
  "Interlaken",
  "Inverness",
  "Ioannina",
  "Iqaluit",
  "Iquitos",
  "Irvine",
  "Irving",
  "Ischgl",
  "Isernia",
  "Lahore",
  "Islamorada",
  "Island Park",
  "Isla Vista",
  "Isle of Palms",
  "Istanbul",
  "İzmir",
  "Izola",
  "Jackson",
  "Jacksonville",
  "Jacksonville Beach",
  "Jaipur",
  "Jakarta",
  "Jefferson City",
  "Jekyll Island",
  "Jena",
  "Jerez de la Frontera",
  "Jersey City",
  "Jerusalem",
  "Johannesburg",
  "Johns Island",
  "Johnson City",
  "Joinville",
  "Jonesboro",
  "Juan Griego",
  "Juan-les-Pins",
  "Juba",
  "Juiz de Fora",
  "Juneau",
  "Jungfrau",
  "Jupiter",
  "Jupiter Island",
  "Jūrmala",
  "Kabul",
  "Kaiserslautern",
  "Kalamata",
  "Kalamazoo",
  "Kamloops",
  "Kampala",
  "Kanchanaburi",
  "Kansas City",
  "Kappl",
  "Kaprun",
  "Islamabad",
  "Karlovy Vary",
  "Karlsruhe",
  "Kassel",
  "Kastoria",
  "Kathmandu",
  "Kaunas",
  "Kavala",
  "Kearney",
  "Keene",
  "Kelowna",
  "Kemer",
  "Kenosha",
  "Key Biscayne",
  "Key Largo",
  "Key West",
  "Khao Lak",
  "Khartoum",
  "Kiawah Island",
  "Kiel",
  "Kigali",
  "Kilkenny",
  "Kill Devil Hills",
  "Kingman",
  "Kingston",
  "Kingston upon Hull",
  "Kingstown",
  "Kinshasa",
  "Kissimmee",
  "Kitchener",
  "Kitty Hawk",
  "Kitzbühel",
  "Klagenfurt",
  "Klaipėda",
  "Knotts Island",
  "Knoxville",
  "Kobe",
  "Koblenz",
  "Kolding",
  "Kolkata",
  "Komotini",
  "Koper",
  "Korčula",
  "Koror",
  "Kos",
  "Košice",
  "Kotor",
  "Krabi",
  "Krakow",
  "Kralendijk",
  "Krefeld",
  "Krk",
  "Kuah",
  "Kuala Lumpur",
  "Kure Beach",
  "Kuşadası",
  "Kuta",
  "Kutná Hora",
  "Kuwait City",
  "Kyiv",
  "Kyoto",
  "Kyrenia",
  "La Ceiba",
  "La Ciotat",
  "La Clusaz",
  "La Laguna",
  "La Maddalena",
  "La Manga",
  "La Paz",
  "La Plagne",
  "La Plata",
  "La Rochelle",
  "La Romana",
  "La Serena",
  "La Seyne-sur-Mer",
  "La Spezia",
  "La Thuile",
  "Laax",
  "Labasa",
  "Labrador City",
  "Labuan Bajo",
  "Lady's Island",
  "Ladysmith",
  "Lafayette",
  "Lagos",
  "Laguna Beach",
  "Karachi",
  "Lakeland",
  "Lalitpur",
  "Lamezia Terme",
  "Lancaster",
  "Landshut",
  "Lansing",
  "L'Aquila",
  "Laredo",
  "Largo",
  "Larnaca",
  "Las Cruces",
  "Las Palmas",
  "Las Vegas",
  "Latina",
  "Laurel Bay",
  "Lausanne",
  "Lautoka",
  "Laval",
  "Lawton",
  "Layton",
  "Le Havre",
  "Le Lavandou",
  "Le Mans",
  "Le Port",
  "Le Puy-en-Velay",
  "Lecce",
  "Lecco",
  "Lech",
  "Leeds",
  "Legian",
  "Legnano",
  "Leicester",
  "Leiden",
  "Leipzig",
  "Lemgo",
  "Leogang",
  "León",
  "Les Arcs",
  "Les Deux Alpes",
  "Les Gets",
  "Les Houches",
  "Les Menuires",
  "Lethbridge",
  "Leuven",
  "Leverkusen",
  "Lexington",
  "Liberec",
  "Libreville",
  "Lichfield",
  "Lido Beach",
  "Lido Key",
  "Liège",
  "Lienz",
  "Liepāja",
  "Lille",
  "Lilongwe",
  "Lima",
  "Limassol",
  "Limerick",
  "Limoges",
  "Lincoln",
  "Lincoln",
  "Lindos",
  "Linz",
  "Lisbon",
  "Lisburn",
  "Little Rock",
  "Liverpool",
  "Livigno",
  "Livorno",
  "Ljubljana",
  "Lloret de Mar",
  "Llucmajor",
  "Loano",
  "Locarno",
  "Lodi",
  "Lodz",
  "Logan",
  "Logroño",
  "Lomé",
  "London",
  "Londrina",
  "Long Beach",
  "Long Branch",
  "Longboat Key",
  "Longport",
  "Longview",
  "Lorain",
  "Los Alamos",
  "Los Angeles",
  "Los Cabos",
  "Los Cristianos",
  "Los Gatos",
  "Louisville",
  "Lourdes",
  "Loutraki",
  "Louvain-la-Neuve",
  "Lowell",
  "Lower Grand Lagoon",
  "Luanda",
  "Lubbock",
  "Lübeck",
  "Lublin",
  "Lucca",
  "Lucerne",
  "Lugano",
  "Luganville",
  "Lund",
  "Lusaka",
  "Luxembourg",
  "Luxor",
  "Lyon",
  "Maastricht",
  "Macerata",
  "Machu Picchu",
  "Macon",
  "Madera",
  "Madison",
  "Madonna di Campiglio",
  "Madrid",
  "Magaluf",
  "Magdeburg",
  "Mahón",
  "Mainz",
  "Majuro",
  "Makarska",
  "Malabo",
  "Malaga",
  "Malang",
  "Maldonado",
  "Malé",
  "Malia",
  "Malibu",
  "Malmö",
  "Mammoth Lakes",
  "Mamoudzou",
  "Manacor",
  "Manado",
  "Managua",
  "Manama",
  "Manchester",
  "Máncora",
  "Mandalika",
  "Manhattan Beach",
  "Manhattan, KS",
  "Manila",
  "Mannheim",
  "Manosque",
  "Manteo",
  "Mantua",
  "Maputo",
  "Mar del Plata",
  "Maracaibo",
  "Marathon",
  "Marbella",
  "Marco Island",
  "Margate City",
  "Maria Alm",
  "Maribor",
  "Marigot",
  "Marina del Rey",
  "Markham",
  "Marmaris",
  "Maroochydore",
  "Marquette",
  "Marrakesh",
  "Marsa Alam",
  "Marsala",
  "Marseille",
  "Martigues",
  "Masaya",
  "Maseru",
  "Maspalomas",
  "Massa",
  "Mata Utu",
  "Mataram",
  "Matera",
  "Mayrhofen",
  "Mazara del Vallo",
  "Mbabane",
  "McKinney",
  "Mechelen",
  "Medan",
  "Medellín",
  "Medford",
  "Megève",
  "Melbourne",
  "Memphis",
  "Menton",
  "Merano",
  "Merced",
  "Meribel",
  "Mérida",
  "Meridian",
  "Merritt Island",
  "Mesa",
  "Messina",
  "Mestre",
  "Metz",
  "Mexico City",
  "Miami",
  "Middelburg",
  "Midland",
  "Mijas",
  "Milan",
  "Milford",
  "Millau",
  "Milwaukee",
  "Mindelo",
  "Minneapolis",
  "Minot",
  "Minsk",
  "Miquelon",
  "Miramar",
  "Miramar Beach",
  "Mishawaka",
  "Mississauga",
  "Missoula",
  "Moab",
  "Mobile",
  "Modena",
  "Modesto",
  "Modica",
  "Moena",
  "Mogadishu",
  "Mogi das Cruzes",
  "Mombasa",
  "Monaco City",
  "Mönchengladbach",
  "Moncton",
  "Monrovia",
  "Mons",
  "Monschau",
  "Montauk",
  "Montecito",
  "Monte Carlo",
  "Monte Rosa",
  "Montego Bay",
  "Montepulciano",
  "Monterey",
  "Montevideo",
  "Montgomery",
  "Montluçon",
  "Montpelier",
  "Montpellier",
  "Montreal",
  "Montreux",
  "Monza",
  "Moose Jaw",
  "Moraira",
  "Moreno Valley",
  "Morgantown",
  "Moroni",
  "Morro Bay",
  "Morzine",
  "Moscow",
  "Moss Landing",
  "Mount Vernon",
  "Mountain View",
  "Moutier",
  "Mulhouse",
  "Mumbai",
  "Munich",
  "Münster",
  "Murcia",
  "Murfreesboro",
  "Murter",
  "Mykonos",
  "Mytilene",
  "Nadi",
  "Nafplio",
  "Nagoya",
  "Nags Head",
  "Nairobi",
  "Namur",
  "Nanaimo",
  "Nancy",
  "Nantes",
  "Napa",
  "Naples",
  "Narbonne",
  "Narva",
  "Nashua",
  "Nashville",
  "Nassau",
  "Navarre",
  "Navarre Beach",
  "Naxos",
  "Nazareth",
  "N'Djamena",
  "Negril",
  "Neiafu",
  "Nelson",
  "Nerja",
  "Netanya",
  "Nevers",
  "New Haven",
  "New London",
  "New Orleans",
  "New Smyrna Beach",
  "New York City",
  "Newark",
  "Newcastle",
  "Newport",
  "Newport Beach",
  "Newport News",
  "Newry",
  "Ngerulmud",
  "Nha Trang",
  "Niagara Falls",
  "Niamey",
  "Nice",
  "Nicosia",
  "Nijmegen",
  "Nimes",
  "Niort",
  "Noosa Heads",
  "Norfolk",
  "Normal",
  "Norman",
  "North Captiva Island",
  "North Las Vegas",
  "North Port",
  "North Topsail Beach",
  "North Wildwood",
  "Norwalk",
  "Norwich",
  "Nottingham",
  "Nouakchott",
  "Nouméa",
  "Novara",
  "Novigrad",
  "Nukuʻalofa",
  "Nukunonu",
  "Nuoro",
  "Nürnberg",
  "Nur-Sultan",
  "Nusa Dua",
  "Nuuk",
  "Nyon",
  "Oak Island",
  "Oakland",
  "Oakville",
  "Oaxaca",
  "Obergurgl",
  "Oberhausen",
  "Ocala",
  "Ocean City",
  "Ocean Grove",
  "Ocean Isle Beach",
  "Oceanside",
  "Ocho Rios",
  "Ocracoke Island",
  "Odense",
  "Odessa",
  "Ogden",
  "Ohomo",
  "Oia",
  "Okaloosa Island",
  "Oklahoma City",
  "Olbia",
  "Oldenburg",
  "Olomouc",
  "Olympia",
  "Omaha",
  "Omoa",
  "Opatija",
  "Orange Beach",
  "Oranjestad",
  "Orem",
  "Oristano",
  "Orlando",
  "Orléans",
  "Ortisei",
  "Osaka",
  "Oshawa",
  "Oshkosh",
  "Oslo",
  "Osnabrück",
  "Ostrava",
  "Otepa",
  "Ottawa",
  "Ouagadougou",
  "Oulu",
  "Ourense",
  "Overland Park",
  "Oviedo",
  "Owensboro",
  "Oxford",
  "Oxnard",
  "Pacific Grove",
  "Padang",
  "Paderborn",
  "Padova",
  "Pago Pago",
  "Pahua",
  "Palanga",
  "Palavas-les-Flots",
  "Palembang",
  "Palermo",
  "Palikir",
  "Palm Bay",
  "Palm Beach",
  "Palm Springs",
  "Palma de Mallorca",
  "Palma Nova",
  "Palmetto",
  "Palmetto Dunes",
  "Palo Alto",
  "Pamandzi",
  "Pamplona",
  "Panama City",
  "Panama City Beach",
  "Papeete",
  "Paphos",
  "Paradiski",
  "Paralia",
  "Paramaribo",
  "Parikia",
  "Paris",
  "Parkersburg",
  "Parksville",
  "Parma",
  "Pärnu",
  "Parris Island",
  "Pasadena",
  "Passo del Tonale",
  "Passo Rolle",
  "Paterson",
  "Patras",
  "Pattaya",
  "Pau",
  "Pavia",
  "Pawleys Island",
  "Peel",
  "Peguera",
  "Pembroke Pines",
  "Peniscola",
  "Pensacola",
  "Pensacola Beach",
  "Peoria",
  "Perast",
  "Perdido Key",
  "Périgueux",
  "Perpignan",
  "Perros-Guirec",
  "Perth",
  "Perugia",
  "Pesaro",
  "Pescara",
  "Pescasseroli",
  "Petah Tikva",
  "Peterborough",
  "Petra",
  "Petrovac",
  "Pforzheim",
  "Phang Nga",
  "Phetchabun",
  "Philadelphia",
  "Philipsburg",
  "Phoenix",
  "Phuket City",
  "Piacenza",
  "Pierre",
  "Pine Bluff",
  "Pine Knoll Shores",
  "Piraeus",
  "Piran",
  "Pisa",
  "Pismo Beach",
  "Pistoia",
  "Pittsburgh",
  "Placencia",
  "Plano",
  "Playa Blanca",
  "Playa de las Américas",
  "Playa del Carmen",
  "Pleasure Point",
  "Plovdiv",
  "Plymouth",
  "Plzeň",
  "Podgorica",
  "Point Lookout",
  "Pointe-à-Pitre",
  "Poitiers",
  "Pollença",
  "Pompano Beach",
  "Pontevedra",
  "Pordenone",
  "Poreč",
  "Porlamar",
  "Port Alberni",
  "Port Angeles",
  "Port Charlotte",
  "Port d'Andratx",
  "Port Louis",
  "Port Moresby",
  "Port of Spain",
  "Port Royal Town",
  "Port St. Lucie",
  "Port Townsend",
  "Port Vila",
  "Port-au-Prince",
  "Portimão",
  "Portland",
  "Porto",
  "Porto Cervo",
  "Porto Cristo",
  "Porto Torres",
  "Portocolom",
  "Portoferraio",
  "Portofino",
  "Porto-Novo",
  "Portorož",
  "Porto-Vecchio",
  "Portsmouth",
  "Portsmouth Island",
  "Positano",
  "Potenza",
  "Potsdam",
  "Pouheva",
  "Poznan",
  "Pozzuoli",
  "Prague",
  "Praia",
  "Praia da Rocha",
  "Prato",
  "Prescott",
  "Preston",
  "Pretoria",
  "Prince Albert",
  "Prince George",
  "Prince Rupert",
  "Pristina",
  "Propriano",
  "Protaras",
  "Providence",
  "Provincetown",
  "Provo",
  "Pueblo",
  "Puerto Baquerizo Moreno",
  "Puerto Cortés",
  "Puerto de la Cruz",
  "Puerto la Cruz",
  "Puerto Plata",
  "Puerto Princesa",
  "Puerto Rico de Gran Canaria",
  "Puerto Vallarta",
  "Pula",
  "Punta Arenas",
  "Punta Cana",
  "Punta del Este",
  "Punta Gorda",
  "Pyeongchang",
  "Pyongyang",
  "Quarteira",
  "Quebec",
  "Quetzaltenango",
  "Quezon City",
  "Quimper",
  "Quito",
  "Quogue",
  "Rabat",
  "Racine",
  "Ragusa",
  "Railay Beach",
  "Raleigh",
  "Ramallah",
  "Ramsey",
  "Rancho Cucamonga",
  "Randers",
  "Rapallo",
  "Rapid City",
  "Ras al-Khaimah",
  "Ras Sedr",
  "Ratingen",
  "Ravello",
  "Ravenna",
  "Rayong",
  "Reading",
  "Red Deer",
  "Redding",
  "Redondo Beach",
  "Regensburg",
  "Reggio Calabria",
  "Reggio Emilia",
  "Regina",
  "Rehovot",
  "Reims",
  "Rennes",
  "Reno",
  "Rethymno",
  "Reus",
  "Reutlingen",
  "Reykjavik",
  "Rhodes",
  "Richmond",
  "Rieti",
  "Riga",
  "Rijeka",
  "Rikitea",
  "Rimini",
  "Rio de Janeiro",
  "Riomaggiore",
  "Rishon LeZion",
  "Rivas",
  "Riverside",
  "Riviera Maya",
  "Road Town",
  "Roanoke",
  "Rocamadour",
  "Rochester",
  "Rock Hill",
  "Rockford",
  "Rockville",
  "Rodanthe",
  "Rodez",
  "Rogers",
  "Rome",
  "Ronda",
  "Rosario",
  "Roseau",
  "Roskilde",
  "Rostock",
  "Roswell",
  "Rotoava",
  "Rotterdam",
  "Roubaix",
  "Rouen",
  "Rovigo",
  "Rovinj",
  "Rutland",
  "Sa Coma",
  "Sa Pobla",
  "Saalbach",
  "Saarbrücken",
  "Saas-Fee",
  "Sacramento",
  "Safaga",
  "Sag Harbor",
  "Sagaponack",
  "Saguenay",
  "Saint John",
  "Saint Paul",
  "Saint Petersburg",
  "Saint-Benoît",
  "Saint-Brieuc",
  "Saint-Denis",
  "Sainte-Maxime",
  "Saintes-Maries-de-la-Mer",
  "Saint-Étienne",
  "Saint-Jean-Cap-Ferrat",
  "Saint-Jean-sur-Richelieu",
  "Saint-Jérôme",
  "Saint-Joseph",
  "Saint-Laurent-du-Maroni",
  "Saint-Leu",
  "Saint-Malo",
  "Saint-Paul",
  "Saint-Pierre",
  "Saint-Tropez",
  "Salamanca",
  "Salem",
  "Salerno",
  "Salinas",
  "Salisbury",
  "Salou",
  "Salt Lake City",
  "Salta",
  "Salter Path",
  "Salvador",
  "Salvo",
  "Salzburg",
  "Samaná",
  "San Angelo",
  "San Antonio",
  "San Bernardino",
  "San Clemente",
  "San Cristóbal",
  "San Diego",
  "San Fernando",
  "San Francisco",
  "San Jose",
  "San Juan",
  "San Juan del Sur",
  "San Lorenzo",
  "San Luis Obispo",
  "San Marino",
  "San Mateo",
  "San Miguel",
  "San Pedro",
  "San Pedro de Atacama",
  "San Pedro Sula",
  "San Rafael",
  "San Salvador",
  "San Sebastián",
  "Sanaa",
  "Sandbridge",
  "Sanford",
  "Sanibel Island",
  "Sanremo",
  "Sant Antoni de Portmany",
  "Santa Ana",
  "Santa Barbara",
  "Santa Clara",
  "Santa Clarita",
  "Santa Cruz",
  "Santa Cruz de la Sierra",
  "Santa Cruz de Tenerife",
  "Santa Eulària des Riu",
  "Santa Fe",
  "Santa Lucía",
  "Santa Margherita Ligure",
  "Santa Maria",
  "Santa Monica",
  "Santa Pola",
  "Santa Ponsa",
  "Santa Rosa",
  "Santa Tecla",
  "Santander",
  "Santanyí",
  "Santiago",
  "Santiago de Compostela",
  "Santo Domingo",
  "Sanur",
  "Sao Paulo",
  "São Tomé",
  "Sapporo",
  "Sarajevo",
  "Sarasota",
  "Saratoga Springs",
  "S'Arenal",
  "Sariaya",
  "Sarlat-la-Canéda",
  "Saskatoon",
  "Sassari",
  "Sault Ste. Marie",
  "Saumur",
  "Sausalito",
  "Savannah",
  "Savona",
  "Savusavu",
  "Schaffhausen",
  "Schenectady",
  "Schladming",
  "Schwerin",
  "Scottsdale",
  "Scranton",
  "Sea Island",
  "Sea Isle City",
  "Seabrook Island",
  "Seal Beach",
  "Seaside",
  "Seattle",
  "Sedona",
  "Seefeld",
  "Segovia",
  "Semarang",
  "Seminyak",
  "Seoul",
  "Serre Chevalier",
  "Serbia",
  "Sète",
  "Seville",
  "Shanghai",
  "Sharjah",
  "Sharm el-Sheikh",
  "Sheffield",
  "Shell Point",
  "Shelter Cove",
  "Shenzhen",
  "Sherbrooke",
  "Shinnecock Hills",
  "Ship Bottom",
  "Shreveport",
  "Šiauliai",
  "Šibenik",
  "Side",
  "Siegen",
  "Siena",
  "Siesta Key",
  "Sineu",
  "Singapore",
  "Singaraja",
  "Sion",
  "Sioux City",
  "Sioux Falls",
  "Sitges",
  "Skiathos",
  "Skopje",
  "Sofia",
  "Sölden",
  "Söll",
  "Soller",
  "Solothurn",
  "Sondrio",
  "Sopot",
  "Sorocaba",
  "Sorrento",
  "South Beach",
  "South Bend",
  "Southampton",
  "Southern Shores",
  "Split",
  "Spokane",
  "Springdale",
  "Springfield",
  "Springs",
  "St Albans",
  "St George's",
  "St Pete Beach",
  "St. Albans",
  "St. Anton",
  "St. Augustine",
  "St. Augustine Beach",
  "St. Catharines",
  "St. Cloud",
  "St. Gallen",
  "St. George",
  "St. George Island",
  "St. John's",
  "St. Louis",
  "St. Moritz",
  "St. Petersburg",
  "St. Simons Island",
  "Stamford",
  "Stanley",
  "Stavanger",
  "Steinbach",
  "Stillwater",
  "Stinson Beach",
  "Stirling",
  "Stock Island",
  "Stockholm",
  "Stockton",
  "Stoke-on-Trent",
  "Stone Harbor",
  "Strasbourg",
  "Strathmere",
  "Stuttgart",
  "Sucre",
  "Sudbury",
  "Suez",
  "Sukhothai",
  "Sukhumi",
  "Sullivan's Island",
  "Summerside",
  "Sumter",
  "Sunderland",
  "Sunnyvale",
  "Sunset Beach",
  "Sunshine Coast",
  "Superior",
  "Surabaya",
  "Surf City",
  "Surrey",
  "Suva",
  "Sveti Stefan",
  "Swansea",
  "Sydney",
  "Syracuse",
  "Szczecin",
  "Taba",
  "Tacloban",
  "Tacoma",
  "Tagbilaran",
  "Taiohae",
  "Taipei",
  "Tallahassee",
  "Tallinn",
  "Tampa",
  "Tampere",
  "Tamworth",
  "Tangier",
  "Taormina",
  "Taranto",
  "Tarifa",
  "Tarragona",
  "Tartu",
  "Tashkent",
  "Tauplitz",
  "Tauranga",
  "Tavira",
  "Tbilisi",
  "Tegucigalpa",
  "Tel Aviv",
  "Temecula",
  "Tempe",
  "Tenukupara",
  "Tepukamaruia",
  "Teramo",
  "Ternate",
  "Terni",
  "Texarkana AR",
  "Texarkana TX",
  "The Bottom",
  "The Hague",
  "The Valley",
  "The Wildwoods",
  "The Woodlands",
  "Thessaloniki",
  "Thimphu",
  "Thunder Bay",
  "Tignes",
  "Tijuana",
  "Tilburg",
  "Timmins",
  "Tinos",
  "Tirana",
  "Tivat",
  "Tivoli",
  "Tokyo",
  "Toledo",
  "Tooele",
  "Toowoomba",
  "Topeka",
  "Topsail Beach",
  "Toronto",
  "Torre del Greco",
  "Torre del Mar",
  "Torremolinos",
  "Torrevieja",
  "Tórshavn",
  "Toruń",
  "Tossa de Mar",
  "Toulon",
  "Toulouse",
  "Tours",
  "Townsville",
  "Trani",
  "Trapani",
  "Treasure Island",
  "Trento",
  "Trenton",
  "Treviso",
  "Trier",
  "Trieste",
  "Tripoli",
  "Trogir",
  "Trois-Rivières",
  "Tromsø",
  "Trondheim",
  "Trouville-sur-Mer",
  "Troy",
  "Troyes",
  "Trujillo",
  "Tucson",
  "Tuherahera",
  "Tui",
  "Tulsa",
  "Tulum",
  "Tupapati",
  "Turin",
  "Turku",
  "Tuscaloosa",
  "Twin Falls",
  "Two Harbors",
  "Tybee Island",
  "Tyler",
  "Ubud",
  "Udine",
  "Udon Thani",
  "Ukiah",
  "Ulaanbaatar",
  "Ulcinj",
  "Ulm",
  "Umag",
  "Upper Grand Lagoon",
  "Uppsala",
  "Urbino",
  "Urubamba",
  "Ushuaia",
  "Utica",
  "Utrecht",
  "Vaduz",
  "Vaitape",
  "Val d’Isère",
  "Val di Fassa",
  "Val Gardena",
  "Val Thorens",
  "Valence",
  "Valencia",
  "Valladolid",
  "Valldemossa",
  "Valle Isarco",
  "Vallejo",
  "Valletta",
  "Valparaíso",
  "Vancouver",
  "Varazze",
  "Varese",
  "Varna",
  "Vaughan",
  "Vejle",
  "Venice ",
  "Ventimiglia",
  "Ventnor City",
  "Ventspils",
  "Ventura",
  "Verbania",
  "Verbier",
  "Vercelli",
  "Vero Beach",
  "Verona",
  "Versailles",
  "Vevey",
  "Viareggio",
  "Vibo Valentia",
  "Viborg",
  "Vicenza",
  "Vichy",
  "Victoria",
  "Victorville",
  "Vienna",
  "Vigan",
  "Vigo",
  "Vilamoura",
  "Vilano Beach",
  "Villach",
  "Villefranche-sur-Mer",
  "Vilnius",
  "Viña del Mar",
  "Virginia Beach",
  "Visalia",
  "Viterbo",
  "Vitoria-Gasteiz",
  "Volos",
  "Vrsar",
  "Waco",
  "Wainscott",
  "Wakefield",
  "Wanchese",
  "Warsaw",
  "Warth",
  "Washington D.C.",
  "Water Mill",
  "Waterford",
  "Watertown",
  "Watsonville",
  "Waukegan",
  "Waukesha",
  "Waves",
  "Wellington",
  "Wengen",
  "Weno",
  "West Hampton Dunes",
  "West Lafayette",
  "West Palm Beach",
  "West Wildwood",
  "Westendorf",
  "Westhampton",
  "Westhampton Beach",
  "Westminster",
  "Weston",
  "Wheeling",
  "White Plains",
  "Whitehorse",
  "Wichita",
  "Wichita Falls",
  "Wiesbaden",
  "Wildwood",
  "Wildwood Crest",
  "Wilkes-Barre",
  "Willemstad",
  "Williams",
  "Wilmington",
  "Winchester",
  "Windhoek",
  "Windsor",
  "Winnipeg",
  "Winslow",
  "Winston–Salem",
  "Winterthur",
  "Wolfsburg",
  "Wollongong",
  "Wolverhampton",
  "Woodburn",
  "Worcester",
  "Worthing",
  "Wrightsville Beach",
  "Wroclaw",
  "Wuppertal",
  "Würzburg",
  "Yakima",
  "Yamoussoukro",
  "Yaoundé",
  "Yaren",
  "Yellowknife",
  "Yerevan",
  "Yogyakarta",
  "Yokohama",
  "Yonkers",
  "York",
  "Youngstown",
  "Yuma",
  "Zadar",
  "Zagreb",
  "Zakopane",
  "Zamboanga City",
  "Zanzibar",
  "Zaragoza",
  "Zell am See",
  "Zell am Ziller",
  "Zermatt",
  "Zug",
  "Zurich",
  "Zwickau",
  "Zwolle",
];
export const arrayOfTopics = [
  "Abortion",
  "Academics",
  "Accounting",
  "Acid Reflux",
  "ACT",
  "Activism",
  "Acupuncture",
  "Acute Lymphocytic Leukemia",
  "ADHD",
  "Addiction",
  "Adoption",
  "Advanced Placement",
  "Advertising",
  "Affirmative Action",
  "Affordable Care Act",
  "aging",
  "AIDS/ HIV",
  "Airline Credit Cards",
  "Airlines",
  "Alaska Vacations",
  "Alcohol",
  "All-Inclusive Vacations",
  "Allergic Rhinitis",
  "allergies",
  "altcoin",
  "Alternative Fuels",
  "Alternative Medicine",
  "Alternative Minimum Tax",
  "Alzheimer's Disease",
  "Ambien",
  "American Health Care Act",
  "Anaphylactic Shock",
  "Animal Cruelty",
  "Animals",
  "annuities",
  "Anthrax",
  "Anthropology",
  "anti-inflammatory",
  "Antibiotics",
  "Antihistamines",
  "Antioxidants",
  "Anxiety",
  "Aortic Aneurysm",
  "Appearance",
  "Arab region universities",
  "Architecture",
  "Arizona Vacations",
  "Arrhythmia",
  "Art",
  "Arthritis",
  "Artificial Intelligence",
  "Arts And Sciences Graduate Programs",
  "Aspirin",
  "Assassinations",
  "assisted living",
  "asthma",
  "Autism",
  "Autoimmune Diseases",
  "autonomous vehicles",
  "Baby Boomers",
  "Back Problems",
  "Back To School",
  "Bacteria",
  "Bad Credit Credit Cards",
  "Bailout",
  "Balance Transfer Credit Cards",
  "Banking",
  "Bankruptcy",
  "Baseball",
  "Basketball",
  "Beach Vacations",
  "The Beatles",
  "Bees",
  "Behavior",
  "Benefits",
  "Benghazi",
  "Berlin Wall",
  "Biologic Drugs",
  "Biology",
  "biotechnology",
  "Bipolar Disorder",
  "Bird Flu",
  "Birds",
  "Birth",
  "Birth Control",
  "Birth Rate",
  "Bitcoin",
  "Black Friday",
  "BlackBerry",
  "blockchain",
  "Blogs",
  "Blood Disorders",
  "Blood Sugar",
  "Body Fat",
  "Body Image",
  "Bonds",
  "Bone Joint Health",
  "Bones",
  "Books",
  "Boston Marathon Bombing",
  "BPA",
  "Brain Cancer",
  "brain health",
  "Brain Tumor",
  "Breast Cancer",
  "Brexit",
  "Broad Prize For Urban Education",
  "Brokers",
  "Bronchitis",
  "Bronchodilators",
  "Budget Travel",
  "Bullying",
  "Business",
  "Business Credit Cards",
  "Business Growth",
  "Business School",
  "business travel",
  "C Sections",
  "Cabinet Members",
  "Caffeine",
  "Calcium",
  "California Vacations",
  "Cameras",
  "Campaign Finance",
  "Campaigns",
  "Camping Vacations",
  "Campus Health",
  "campus life",
  "Cancer",
  "Cancer Screening And Treatment",
  "Candidates",
  "capital gains",
  "capital gains taxes",
  "Capitalism",
  "Car Manufacturers",
  "Cardiology",
  "Cardiomyopathy",
  "Careers",
  "Caregiving",
  "Caribbean Vacations",
  "Cars",
  "Cash Back Credit Cards",
  "CBD",
  "Celebrities",
  "Celiac Disease",
  "Cervical Cancer",
  "Charter Schools",
  "Cheating",
  "chemical weapons",
  "Chemistry",
  "Chemotherapy",
  "Children",
  "children's health",
  "Cholesterol",
  "Christianity",
  "Christmas",
  "Chronic Lymphocytic Leukemia",
  "Circulatory Conditions",
  "Circumcision",
  "Cities",
  "Civil Rights",
  "Civil War",
  "Clinical Trials",
  "Cloning",
  "Clothing",
  "cloud stocks",
  "Coal",
  "Cocaine",
  "Cold War",
  "College Admissions",
  "College Applications",
  "College Athletics",
  "College Endowments",
  "College Majors",
  "College Search",
  "Colleges",
  "Colon Cancer",
  "Colon Health",
  "Colonoscopy",
  "Colorado Vacations",
  "Commodities",
  "Common Cold",
  "Common Core",
  "Communism",
  "Community",
  "Community Colleges",
  "Community Service",
  "Computers",
  "Concussions",
  "Congenital Heart Disease",
  "Congress",
  "Conjunctivitis",
  "Conservatives",
  "Constipation",
  "Constitution",
  "Consultants",
  "Consumers",
  "Continuing Education",
  "Convention2016",
  "Cooking",
  "COPD",
  "Copyright",
  "Coronary Artery Disease",
  "Coronavirus",
  "Company Culture",
  "Corporate Earnings",
  "Corporate Taxes",
  "Corruption",
  "Cosmetic Procedures",
  "Cosmetics",
  "Counseling",
  "Couples Vacations",
  "Courts",
  "Cover Letters",
  "CPAC",
  "Credit",
  "Credit Cards",
  "Credit Monitoring",
  "Credit Reports",
  "Credit Scores",
  "Credit Unions",
  "Crime",
  "Criminal Justice Programs",
  "Crohn's Disease",
  "Cruises",
  "Cryptocurrency",
  "CT scans",
  "Culinary School",
  "currency",
  "Customer Service",
  "Cybersecurity",
  "Cycling",
  "DACA",
  "Death",
  "Death Penalty",
  "Debates",
  "Debit Cards",
  "Debt",
  "decentralized finance",
  "Defense Spending",
  "Deficit And National Debt",
  "Deforestation",
  "Dementia",
  "Democracy",
  "Democratic National Convention",
  "Democratic Party",
  "Demographics",
  "Dental Health",
  "dentists",
  "Depression",
  "Dermatology",
  "Detainees",
  "Developing Countries",
  "diabetes",
  "Diabetes Type 1",
  "Diabetes Type 2",
  "diet and nutrition",
  "Diets",
  "Digestive Disorders",
  "Digestive Health",
  "Digital Piracy",
  "Dinosaurs",
  "Diplomacy",
  "Disability",
  "Disarmament",
  "Discrimination",
  "Diseases",
  "Disney Vacations",
  "Diversity",
  "dividends",
  "Divorce",
  "DIY",
  "Dizziness",
  "DNA tests",
  "Doctors",
  "Dogs",
  "Domestic Abuse",
  "Dow Jones Industrial Average",
  "Down Syndrome",
  "DREAM Act",
  "Driving",
  "Drones",
  "Dropout Rates",
  "Drought",
  "Drug Abuse",
  "Drugs",
  "e-commerce",
  "E. coli",
  "Ear Nose And Throat Conditions",
  "Early Childhood Education",
  "Earmarks",
  "Earth Day",
  "Earthquakes",
  "Eating Disorders",
  "Ebola",
  "Economic Austerity",
  "Economic Depression",
  "Economic Growth",
  "Economic Stimulus",
  "Economics",
  "Economy",
  "Eczema",
  "Education",
  "Education Graduate School",
  "Education Policy",
  "Education Reform",
  "Elections",
  "Electoral College",
  "electric vehicles",
  "Electricity",
  "Elementary School",
  "Email",
  "Emergency Planning",
  "Emerging Markets",
  "Emmys",
  "Employment",
  "Endangered Species",
  "Endocrinology",
  "Endometrial Cancer",
  "Energy",
  "Energy Efficiency",
  "Energy Policy And Climate Change",
  "Engineering",
  "Engineering Graduate School",
  "Enlarged Heart",
  "Entertainment",
  "Entrepreneurship",
  "Environment",
  "Epilepsy",
  "Erectile Dysfunction",
  "ESG investing",
  "Espionage",
  "Estate Taxes",
  "Estrogen",
  "Ethanol",
  "Ethereum",
  "Ethics",
  "Euro",
  "Europe Vacations",
  "Evangelicals",
  "Every Student Succeeds Act",
  "Evolution",
  "Exchange Traded Funds",
  "Executive Orders",
  "Executive Pay",
  "Executives",
  "exercise and fitness",
  "Existing Home Sales",
  "Exports",
  "Extinction",
  "Extraterrestrials",
  "Eye Health",
  "Eye Problems",
  "FAFSA",
  "Fair Credit Credit Cards",
  "Fall Vacations",
  "Family",
  "Family Health",
  "Family Vacations",
  "Farm Bill",
  "Farming",
  "Fashion",
  "Fatigue",
  "Federal Budget",
  "Federal Taxes",
  "Female Voters",
  "Feminism",
  "Fever",
  "Fibroids",
  "Fibromyalgia",
  "Financial Advisors",
  "Financial Aid",
  "Financial Goals",
  "Financial Literacy",
  "Financial Regulation",
  "fintech",
  "First Aid",
  "First Ladies",
  "FISA",
  "Fiscal Cliff",
  "Fiscal Policy",
  "Fish",
  "Flexible Spending Accounts",
  "Floods",
  "Florida Vacations",
  "Food Allergies",
  "Food And Drink",
  "Food Safety",
  "Food Stamps",
  "Food Vacations",
  "Foot Problems",
  "Football",
  "For Profit Colleges",
  "Foreclosures",
  "Foreign Aid",
  "Foreign Investment",
  "Foreign Policy",
  "Fracking",
  "Franchising",
  "Fraternities And Sororities",
  "Fraud",
  "Freebies",
  "Freedom of Information Act",
  "Freedom Of Speech",
  "Fuel Efficiency",
  "Fuel Taxes",
  "Fundraising",
  "Funds",
  "Funerals",
  "futures",
  "Gallbladder Problems",
  "Gambling",
  "Games",
  "Gardasil",
  "Gardening",
  "Gas Credit Cards",
  "Gas Prices",
  "Gastroenterology",
  "GDP",
  "Gender",
  "Gender Bias",
  "gene editing",
  "Generation X",
  "Generic Drugs",
  "Genetic Information Nondiscrimination Act",
  "Genetics",
  "Genocide",
  "Genome",
  "Gentrification",
  "Geography",
  "Geology",
  "Georgia Vacations",
  "GERD",
  "Geriatrics",
  "Gestational Diabetes",
  "Gifts",
  "Global Economy",
  "Global Universities",
  "Global Universities",
  "Global Warming",
  "Globalization",
  "Gluten",
  "GMAT",
  "Gold",
  "Golf",
  "Gout",
  "Government",
  "Government Contracts",
  "Government Intervention",
  "Government Shutdown",
  "Governors",
  "GPS",
  "Graduate Schools",
  "Graduation Rates",
  "Graves' Disease",
  "GRE",
  "Great Depression",
  "Greenhouse Gases",
  "Gun Control And Gun Rights",
  "H1N1",
  "Habits",
  "Hair Loss",
  "Hanukkah",
  "Happiness",
  "Hate Crimes",
  "Hawaii Vacations",
  "Hazing",
  "Headaches",
  "health",
  "Health Care",
  "Health Care Reform",
  "health equity",
  "Health Insurance",
  "Hearing Problems",
  "Heart Attacks",
  "heart disease",
  "Heart Failure",
  "Heart Health",
  "Heart Surgery",
  "Heart Transplants",
  "heart-healthy diet",
  "Heating",
  "Heatstroke",
  "Hedge Funds",
  "Hemochromatosis",
  "Hepatitis",
  "Heroin",
  "Hidden Fees",
  "High Blood Pressure",
  "high blood pressure diet",
  "High Credit Limits Cards",
  "High School",
  "high-fiber diet",
  "high-protein diet",
  "Hinduism",
  "Hip Replacement",
  "Hiring",
  "Hispanic Voters",
  "Hispanics",
  "Historically Black Colleges And Universities",
  "History",
  "Hockey",
  "Holiday Shopping",
  "Holidays",
  "Holocaust",
  "Home Improvements",
  "Home Insurance",
  "Home Prices",
  "Home Refinancing",
  "Home Renovations",
  "Home Repair",
  "Homeland",
  "Homelessness",
  "Hormones",
  "Horses",
  "Hospitals",
  "Hotel Credit Cards",
  "Hotels and Resorts",
  "Housing",
  "Housing Market",
  "HRT",
  "Human Body",
  "Human Papillomavirus",
  "Human Rights",
  "Hunting",
  "Hurricane Harvey",
  "Hurricane Irma",
  "Hurricane Katrina",
  "Hurricane Maria",
  "Hurricane Sandy",
  "Hurricanes",
  "Hydrogen",
  "Hysterectomy",
  "Identity Theft",
  "Illinois Vacations",
  "Immigration",
  "Immigration Reform",
  "impact investing",
  "Impeachment",
  "Imports",
  "Inauguration",
  "Income",
  "Income Investing",
  "Income Tax",
  "Incontinence",
  "independent living",
  "Index Funds",
  "Indigestion",
  "Inequality",
  "Infant Mortality",
  "Infants",
  "Infections",
  "infectious diseases",
  "Infertility",
  "Inflation",
  "Influenza",
  "Infrastructure",
  "Injuries",
  "Innovation",
  "Insects",
  "Insomnia",
  "Insurance",
  "Intellectual Property",
  "Interest Rates",
  "Interior Design",
  "International Baccalaureate",
  "International Students",
  "International Trade",
  "International Treaties",
  "Internet",
  "Internships",
  "Interrogations",
  "Interviewing",
  "Investing",
  "Investing for Retirement",
  "Investing Insights",
  "invisible braces",
  "Iowa Caucus",
  "iPhone",
  "iPods",
  "IPOs",
  "Iraq War",
  "IRAs",
  "Irritable Bowel Syndrome",
  "Islam",
  "January 6th",
  "Jewelry",
  "Applying",
  "Jobs Reports",
  "Journalism",
  "Judaism",
  "Juneteenth",
  "junk bonds",
  "K 12 Education",
  "Keystone XL Pipeline",
  "Kidnapping",
  "Kidney Problems",
  "Kidney Transplants",
  "Knee Replacement",
  "Korean War",
  "Kurds",
  "Kyoto Protocol",
  "Labor",
  "Lake Vacations",
  "Landlording",
  "landscaping",
  "Languages",
  "Laptops",
  "Law",
  "Law School",
  "Lawsuits",
  "Lead Poisoning",
  "Leadership",
  "Legislation",
  "Leukemia",
  "Lgbt Rights",
  "Liberals",
  "Libor",
  "Libraries",
  "Life Insurance",
  "Liver Problems",
  "Loans",
  "Lobbying",
  "long-term care",
  "Longevity",
  "Lottery",
  "Louisiana Vacations",
  "Low Interest Credit Cards",
  "low-calorie diet",
  "LSAT",
  "Lung Cancer",
  "Lung Disease",
  "Lung Transplants",
  "Lupus",
  "Luxury",
  "Lyme Disease",
  "Macular Degeneration",
  "Magazines",
  "Malaria",
  "Mammogram",
  "Management",
  "Mantle Cell Lymphoma",
  "Manufacturing",
  "March Madness",
  "Marijuana",
  "Marketing",
  "Marriage",
  "Massage",
  "Math",
  "MBAs",
  "MCAT",
  "Measles",
  "Media",
  "Medicaid",
  "Medical Marijuana",
  "Medical Prevention",
  "Medical Quality",
  "Medical Records",
  "Medical School",
  "Medical Screening",
  "Medical Technology",
  "Medical Travel",
  "Medicare",
  "Medicine",
  "Meditation",
  "Meetings",
  "melanoma",
  "Memorial Day",
  "Memory",
  "memory care",
  "men's health",
  "Meningitis",
  "Menopause",
  "Mental Health",
  "Mergers",
  "Metabolic Syndrome",
  "Metabolism",
  "Metastatic Prostate Cancer",
  "metaverse",
  "Methodology",
  "Michigan Vacations",
  "Mid-Atlantic Vacations",
  "Middle School",
  "Mideast Peace",
  "Midwest Vacations",
  "Military",
  "Military Bases",
  "Military Courts",
  "Military Credit Cards",
  "Military Strategy",
  "Milk",
  "Millennials",
  "Minimum Wage",
  "Mining",
  "Minority Students",
  "Missiles",
  "Mobility",
  "Monetary Policy",
  "Money",
  "Money Market Funds",
  "monkeypox",
  "Montana Vacations",
  "MOOCs",
  "Mormonism",
  "Mortgages",
  "Mountain Vacations",
  "Movies",
  "Moving",
  "MRSA",
  "Multiple Sclerosis",
  "Mumps",
  "Murder",
  "Muscle Problems",
  "Music",
  "mutual funds",
  "NAFTA",
  "Nasdaq",
  "Nation",
  "National Assessment Of Educational Progress",
  "National Parks",
  "National Security",
  "National Security Terrorism And The Military",
  "Native Americans",
  "Natural Disasters",
  "Natural Gas",
  "Nephrology",
  "Net Neutrality",
  "Networking",
  "Neuroimaging",
  "Neurology",
  "Nevada Vacations",
  "New Deal",
  "New England Vacations",
  "New Hampshire Primaries",
  "New Home Sales",
  "New Jersey Vacations",
  "New Year",
  "New York Vacations",
  "Newspapers",
  "NFTs",
  "No Annual Fee Credit Cards",
  "No Balance Transfer Fees Credit Cards",
  "No Child Left Behind",
  "No Foreign Transaction Fee Credit Cards",
  "Nobel Prize",
  "Nonprofits",
  "Norovirus",
  "North Carolina Vacations",
  "NSAIDs",
  "Nuclear Power",
  "Nuclear Weapons",
  "Nurses",
  "Nursing Homes",
  "Nursing Programs",
  "Obama Administration",
  "Obama Transition",
  "Obesity",
  "Obstetrics And Gynecology",
  "Occupational Health",
  "OCD",
  "Oceans",
  "Offbeat",
  "Ohio Vacations",
  "oil",
  "The Olympics",
  "Oncology",
  "Online Education",
  "Online MBA",
  "Online Savings Accounts",
  "Ophthalmology",
  "Opioids",
  "options",
  "Oral Cancer",
  "Organic Food",
  "Osteoarthritis",
  "Osteopathy",
  "Osteoporosis",
  "Otolaryngology",
  "Outdoor Living",
  "Outsourcing",
  "Ovarian Cancer",
  "Over The Counter Drugs",
  "Pacemakers",
  "Pacific Northwest Vacations",
  "Pain Management",
  "Pancreatic Cancer",
  "Pandemic",
  "Pap Smear",
  "parent loans",
  "Parenting",
  "Paris Terror Attacks",
  "Parkinson's Disease",
  "Passports",
  "Patents",
  "Patient Advice",
  "Patient Safety",
  "Patients",
  "Paying For College",
  "Paying For Community College",
  "Paying For Graduate School",
  "pediatric cardiology",
  "Peer Pressure",
  "Pell Grants",
  "Pending Home Sales",
  "Pennsylvania Vacations",
  "Pensions",
  "performing arts",
  "personal budgets",
  "Personal Finance",
  "Pets",
  "Pharmacies",
  "Philanthropy",
  "Photo Galleries",
  "Physical Therapy",
  "Physics",
  "Pirates",
  "Plagiarism",
  "Plants",
  "Plastic",
  "Plastic Surgery",
  "Pneumonia",
  "Podcasts",
  "Police",
  "Polio",
  "Politics",
  "Polls",
  "Pollution",
  "Polygamy",
  "Population",
  "Populism",
  "Portfolio Management",
  "Poverty",
  "POWs",
  "Prediabetes",
  "Pregnancy",
  "Preschool",
  "Prescription Drugs",
  "President",
  "Presidential Pardon",
  "Presidential Speech Transcripts",
  "Prices",
  "Primaries",
  "Prison Sentences",
  "Prisons",
  "Privacy",
  "Private Schools",
  "Product Safety",
  "Productivity",
  "Products",
  "Profits",
  "Property Taxes",
  "Proposition 8",
  "Prostate",
  "Prostate Cancer",
  "Prosthetics",
  "Prostitution",
  "Protein",
  "Psoriasis",
  "Psoriatic Arthritis",
  "Psychiatry",
  "Psychology",
  "PTSD",
  "Public Health",
  "Public Schools",
  "Pulmonary Fibrosis",
  "Pulmonology",
  "Quality Of Life",
  "Quantitative Easing",
  "U.S. News Quizzes",
  "Race",
  "Racism",
  "Radiation",
  "Radiation Oncology",
  "Radio",
  "Rankings",
  "Real Estate",
  "Rebates",
  "Recalls",
  "Recession",
  "Recipes",
  "Recruiters",
  "Recycling",
  "Refugees",
  "REITs",
  "Relationships",
  "Religion",
  "Renewable Energy",
  "Renting",
  "Republican National Convention",
  "Republican Party",
  "Research",
  "Respiratory Problems",
  "Restaurants",
  "Restless Leg Syndrome",
  "Resumes",
  "Retailers",
  "Retirement",
  "Revenue",
  "Revolutionary War",
  "Rewards Credit Cards",
  "Rheumatoid Arthritis",
  "Rheumatology",
  "Rhodes Scholars",
  "Ritalin",
  "Road Trips",
  "Robots",
  "Running Mates",
  "Russia investigation",
  "Safety",
  "Salaries and Benefits",
  "Sales",
  "Sales Tax",
  "Salmonella",
  "Sarbanes Oxley Act",
  "SAT",
  "Satellites",
  "Saving For College",
  "Savings",
  "Schizophrenia",
  "Scholarships",
  "School Shootings",
  "School Vouchers",
  "Science",
  "Scoliosis",
  "Second Amendment",
  "Second Careers",
  "Secured Credit Cards",
  "Seizures",
  "semiconductors",
  "Senior Citizens",
  "Senior Health",
  "Sensory Problems",
  "sequestration",
  "Sex",
  "Sex Education",
  "Sexism",
  "Sexual Abuse",
  "sexual assault",
  "sexual health",
  "Sexual Misconduct",
  "Sexually Transmitted Diseases",
  "Shingles",
  "Shopping",
  "short squeeze",
  "Sickle Cell Disease",
  "Sign Up Bonus Credit Cards",
  "Sinusitis",
  "Skiing",
  "Skin Cancer",
  "Skin Conditions",
  "Slavery",
  "sleep",
  "Sleep Apnea",
  "Sleep Disorders",
  "Small Business",
  "Smart Cities",
  "Smartphones",
  "Smoking And Tobacco",
  "Soccer",
  "Social Anxiety Disorder",
  "Social Networking",
  "Social Security",
  "Social Security Numbers",
  "Socialism",
  "socially responsible investing",
  "Sociology",
  "Sodium",
  "Software",
  "Solar Energy",
  "Solo Vacations",
  "South Carolina Vacations",
  "Southeast Vacations",
  "Southwest Vacations",
  "Space",
  "Space Station",
  "SPDRs",
  "Special Forces",
  "Speech Problems",
  "Speeches",
  "Sports",
  "Sports Medicine",
  "spring",
  "Spring Vacations",
  "stablecoin",
  "Stafford Loans",
  "Standardized Tests",
  "Starter Cards For Building Credit",
  "Startups",
  "State Budgets",
  "State Law",
  "State Of The Union",
  "Statins",
  "Steel",
  "STEM",
  "Stem Cells",
  "STEM education",
  "STEM jobs",
  "Steroids",
  "Stock Market",
  "Stock Market News",
  "Stress",
  "Stroke",
  "Student Credit Cards",
  "student debt",
  "Student Engagement",
  "Student Loans",
  "Students",
  "Study Abroad",
  "Subprime Mortgages",
  "Sugar",
  "Suicide",
  "Summer",
  "Summer Vacations",
  "super PACs",
  "Superdelegates",
  "Supplements",
  "Surgeon General",
  "Surgery",
  "Surveys",
  "SUVs",
  "Tanning",
  "Target-Date Funds",
  "Tariffs",
  "Tax Code",
  "Tax Cuts",
  "Tax Deductions",
  "Tax Exemptions",
  "Tax Returns",
  "Taxes",
  "Tea Party",
  "Teachers",
  "Technology",
  "Teen Pregnancy",
  "Teens",
  "Telecommuting",
  "telehealth",
  "Telephones",
  "Television",
  "Temporary Employment",
  "Tennessee Vacations",
  "Tennis",
  "Terrorism",
  "Testicular Cancer",
  "Testing",
  "Testosterone",
  "Texas Vacations",
  "Textbooks",
  "Thanksgiving",
  "Theme Park Vacations",
  "Therapy",
  "Thyroid",
  "Tipping",
  "Title IX",
  "TOEFL",
  "Torture",
  "Tours",
  "Toys",
  "Trade",
  "Traffic",
  "Traffic Fatalities",
  "Trafficking",
  "Training",
  "trains",
  "Transfer Students",
  "Transgender People",
  "Transplants",
  "Transportation",
  "Travel",
  "Travel Credit Cards",
  "Travel Gear",
  "Travel Insurance",
  "Travel Rewards",
  "Travel Tips",
  "Tropical Vacations",
  "Troubled Assets Relief Program",
  "Tuberculosis",
  "Tuition",
  "U.S. Attorneys",
  "U.S. intelligence",
  "U.S. West Vacations",
  "Ulcer",
  "Ulcerative Colitis",
  "Unemployment",
  "Unions",
  "United Kingdom Vacations",
  "Unsecured Credit Cards",
  "Urban Planning",
  "US Vacations",
  "Utah Vacations",
  "Vacation Ideas",
  "Vacation Rentals",
  "Vacations",
  "Vaccines",
  "Vaping",
  "vegetarian-friendly diet",
  "Venture Capitalism",
  "Veterans",
  "Viagra",
  "Vice President",
  "Video Games",
  "Vietnam War",
  "Violence",
  "Virginia Vacations",
  "Vitamin D",
  "Vitamins",
  "Volcanoes",
  "Volunteering",
  "Voters",
  "Wages",
  "Wall Street",
  "War Crimes",
  "War In Afghanistan",
  "Washington DC Vacations",
  "Washington State Vacations",
  "Water",
  "Water Park Vacations",
  "Water Safety",
  "Waterboarding",
  "Watergate",
  "Wealth",
  "Weapons",
  "Weather",
  "Websites",
  "Weekend Getaways",
  "Weight Loss",
  "West Nile Virus",
  "Whales",
  "White House",
  "Wi Fi",
  "Wildfires",
  "Wills",
  "wind power",
  "Winter Vacations",
  "Wiretapping",
  "Wisconsin Vacations",
  "Women's Colleges",
  "women's health",
  "Women's Rights",
  "Women’s History",
  "Work Life Balance",
  "Working Women",
  "World",
  "World Cup",
  "World News",
  "World War I",
  "World War II",
  "Yoga",
  "Young Professionals",
  "Young Voters",
  "Zika",
];
export const arrayOfSources = [
  "nytimes.com",
  "cnn.com",
  "foxnews.com",
  "msn.com",
  "people.com",
  "finance.yahoo.com",
  "usatoday.com",
  "news.google.com",
  "nypost.com",
  "dailymail.co.uk",
  "washingtonpost.com",
  "bbc.com",
  "news.yahoo.com",
  "cnbc.com",
  "forbes.com",
  "newsweek.com",
  "theguardian.com",
  "wsj.com",
  "apnews.com",
  "nbcnews.com",
  "cbsnews.com",
  "businessinsider.com",
  "buzzfeed.com",
  "the-sun.com",
  "the-sun.co.uk",
  "politico.com",
];
export const API_KEYS = [
  "0c03528ace2c54f1aa95824cf4c5cbfb4",
  "c0d3302a551442f96101b00eff81423",
  "96c6940895d84e5daaa58f8b9c7ac416",
  "e41cabafe8bb452d86d53ee426db0861",
  "6c4f0ed57a334072a74c6f97f2db7387",
  "db0c7fbf32804a48b0f77ef5cfd42d13",
  "18d7b7a53d1d4a73895037c6d5233fc6",
  "0ccbfc1d3b5e4b73b9546bb32cba38e1",
  "3a2af726275f4895ae195b108889261e",
  "f0d39e242b8a4c5694028c73ce16e662",
  "1df1b843d4074dc58083f8437a59b3b2",
  "8889cbf5a52245e398543f52c6d0bc6a",
  "8043ca8f1412485d8a3011796543a9be",
  "2759f5c9ecb742659e7b1ef9dcee2e9b",
  "f7c85d75d58744e8b68038cb6f4968d3",
  "2d63388910ab47ebb8ba7b5f922b092e",
  "f7d451799ca445c0a4bd4922c91322dd",
];
