export const arrayOfCities = [
  "a",
  "Serbia",
  "coruña",
  "aachen",
  "aarhus",
  "abbeville",
  "aberdeen",
  "(uk)",
  "aberdeen",
  "(south",
  "dakota)",
  "aberdeen",
  "(washington)",
  "abidjan",
  "abilene",
  "abu",
  "dhabi",
  "abuja",
  "acapulco",
  "accra",
  "adamstown",
  "addis",
  "ababa",
  "adelaide",
  "adelboden",
  "agadir",
  "agde",
  "agen",
  "agios",
  "nikolaos",
  "agra",
  "agrigento",
  "agropoli",
  "ahmedabad",
  "aigues-mortes",
  "aix-en-provence",
  "aix-les-bains",
  "ajaccio",
  "ajman",
  "akron",
  "al",
  "ain",
  "alameda",
  "alanya",
  "alaró",
  "albacete",
  "albany",
  "albenga",
  "albi",
  "albufeira",
  "albuquerque",
  "alcudia",
  "aleppo",
  "alessandria",
  "ålesund",
  "alexandria",
  "(u.s.)",
  "alexandria",
  "(egypt)",
  "algeciras",
  "alghero",
  "algiers",
  "alicante",
  "alkmaar",
  "allentown",
  "almaty",
  "alofi",
  "alpe",
  "d'huez",
  "alta",
  "badia",
  "altea",
  "altoona",
  "amagansett",
  "amalfi",
  "amapala",
  "amarillo",
  "ambon",
  "amersfoort",
  "amiens",
  "amman",
  "amsterdam",
  "anaheim",
  "anchorage",
  "ancona",
  "andalo",
  "andermatt",
  "andorra",
  "la",
  "vella",
  "andratx",
  "andria",
  "angeles",
  "city",
  "angers",
  "angoulême",
  "ankara",
  "ann",
  "arbor",
  "anna",
  "maria",
  "city",
  "annapolis",
  "annecy",
  "antalya",
  "antananarivo",
  "antibes",
  "antigua",
  "guatemala",
  "antwerp",
  "anzio",
  "ao",
  "nang",
  "aosta",
  "apeldoorn",
  "apia",
  "appleton",
  "aqaba",
  "aracaju",
  "arcachon",
  "arenzano",
  "arequipa",
  "arezzo",
  "argostoli",
  "arica",
  "arles",
  "arlington",
  "(virginia)",
  "arlington",
  "(texas)",
  "armagh",
  "arnhem",
  "arosa",
  "arras",
  "arrecife",
  "artà",
  "asbury",
  "park",
  "ascoli",
  "piceno",
  "ascona",
  "ashdod",
  "ashgabat",
  "ashkelon",
  "asmara",
  "aspen",
  "asti",
  "astoria",
  "asunción",
  "atafu",
  "athens",
  "athlone",
  "atlanta",
  "atlantic",
  "beach",
  "(new",
  "york)",
  "atlantic",
  "beach",
  "(north",
  "carolina)",
  "atlantic",
  "city",
  "atuona",
  "auckland",
  "augsburg",
  "augusta",
  "(georgia)",
  "augusta",
  "(maine)",
  "aurora",
  "(colorado)",
  "aurora",
  "(illinois)",
  "austin",
  "auxerre",
  "avalon",
  "(california)",
  "avalon",
  "(new",
  "jersey)",
  "avarua",
  "avatoru",
  "aveiro",
  "avellino",
  "avignon",
  "avila",
  "beach",
  "avon",
  "avoriaz",
  "axamer",
  "lizum",
  "ayia",
  "napa",
  "azusa",
  "bad",
  "gastein",
  "bad",
  "hofgastein",
  "baden",
  "baghdad",
  "baiona",
  "bakersfield",
  "baku",
  "bald",
  "head",
  "island",
  "baltimore",
  "bamako",
  "banda",
  "aceh",
  "bandar",
  "seri",
  "begawan",
  "bandol",
  "banff",
  "bangalore",
  "bangkok",
  "bangor",
  "bangui",
  "banjul",
  "bar",
  "bar",
  "harbor",
  "barcelona",
  "bari",
  "barletta",
  "barnegat",
  "light",
  "barnum",
  "island",
  "barrie",
  "barstow",
  "basel",
  "basey",
  "basseterre",
  "basse-terre",
  "bastia",
  "bata",
  "batam",
  "bath",
  "baton",
  "rouge",
  "batu",
  "batumi",
  "bayonne",
  "beach",
  "haven",
  "bear",
  "island",
  "beaufort",
  "beaulieu-sur-mer",
  "beaumont",
  "beaune",
  "beersheba",
  "beijing",
  "beirut",
  "belek",
  "belfast",
  "belfort",
  "belgrade",
  "belize",
  "city",
  "bellingham",
  "bellinzona",
  "belluno",
  "belmopan",
  "belo",
  "horizonte",
  "bemidji",
  "benalmadena",
  "bend",
  "bendigo",
  "benevento",
  "benicàssim",
  "benidorm",
  "bergamo",
  "bergen",
  "bergerac",
  "berkeley",
  "berlin",
  "bern",
  "besançon",
  "bethlehem",
  "beverly",
  "hills",
  "béziers",
  "biarritz",
  "biel/bienne",
  "bielefeld",
  "biella",
  "big",
  "bear",
  "lake",
  "big",
  "pine",
  "key",
  "big",
  "sur",
  "bilbao",
  "billings",
  "biloxi",
  "birmingham",
  "(uk)",
  "birmingham",
  "(u.s.)",
  "bishkek",
  "bismarck",
  "bissau",
  "blanes",
  "bled",
  "blois",
  "bloomington",
  "blumenau",
  "boca",
  "chica",
  "boca",
  "grande",
  "boca",
  "raton",
  "bochum",
  "bodrum",
  "bogotá",
  "boise",
  "bologna",
  "bolzano",
  "bonifacio",
  "bonn",
  "bordeaux",
  "bordighera",
  "bormio",
  "boston",
  "boulder",
  "boulogne-sur-mer",
  "bourges",
  "bowling",
  "green",
  "boynton",
  "beach",
  "bozeman",
  "bradenton",
  "bradenton",
  "beach",
  "bradford",
  "braga",
  "brampton",
  "brandon",
  "brantford",
  "brasilia",
  "bratislava",
  "braunschweig",
  "brazzaville",
  "breda",
  "bregenz",
  "brela",
  "bremen",
  "bremerhaven",
  "brescia",
  "brest",
  "briançon",
  "bridgehampton",
  "bridgeport",
  "bridgetown",
  "brigantine",
  "brighton",
  "brindisi",
  "brisbane",
  "bristol",
  "brixen",
  "brixental",
  "brno",
  "brookings",
  "brownsville",
  "bruges",
  "brunswick",
  "brussels",
  "bucharest",
  "budapest",
  "budva",
  "buenos",
  "aires",
  "buffalo",
  "bujumbura",
  "bukittinggi",
  "burgas",
  "burlington",
  "(u.s.)",
  "burlington",
  "(canada)",
  "burnt",
  "pine",
  "burton",
  "butte",
  "buxton",
  "cabo",
  "san",
  "lucas",
  "cadaqués",
  "cádiz",
  "caen",
  "cagliari",
  "cagnes-sur-mer",
  "cairns",
  "cairo",
  "cala",
  "bona",
  "cala",
  "d'or",
  "cala",
  "millor",
  "cala",
  "ratjada",
  "calais",
  "calella",
  "calgary",
  "cali",
  "caloundra",
  "calp",
  "caltanissetta",
  "calvi",
  "cambridge",
  "(uk)",
  "cambridge",
  "(u.s.)",
  "cambrils",
  "camden",
  "campbell",
  "river",
  "campinas",
  "campobasso",
  "can",
  "pastilla",
  "can",
  "picafort",
  "canazei",
  "canberra",
  "cancun",
  "cannes",
  "cannon",
  "beach",
  "canterbury",
  "canton",
  "canyamel",
  "capdepera",
  "cape",
  "canaveral",
  "cape",
  "coral",
  "cape",
  "may",
  "cape",
  "town",
  "capitola",
  "captiva",
  "caracas",
  "carbonia",
  "carcassonne",
  "cardiff",
  "carlisle",
  "carlsbad",
  "carmel-by-the-sea",
  "carolina",
  "beach",
  "carova",
  "beach",
  "carpi",
  "carpinteria",
  "carrara",
  "carson",
  "city",
  "cartagena",
  "(colombia)",
  "cartagena",
  "(spain)",
  "casablanca",
  "caserta",
  "casper",
  "cassis",
  "castellón",
  "de",
  "la",
  "plana",
  "castelrotto",
  "castletown",
  "castries",
  "caswell",
  "beach",
  "catania",
  "catanzaro",
  "caxias",
  "do",
  "sul",
  "cayenne",
  "cebu",
  "city",
  "cedar",
  "island",
  "cedar",
  "key",
  "cedar",
  "rapids",
  "celle",
  "cervinia",
  "cesena",
  "český",
  "krumlov",
  "çeşme",
  "chamonix",
  "chandler",
  "chania",
  "charleroi",
  "charleston",
  "(west",
  "virginia)",
  "charleston",
  "(south",
  "carolina)",
  "charlestown",
  "charlotte",
  "charlotte",
  "amalie",
  "charlottetown",
  "chartres",
  "chatham",
  "chattanooga",
  "chelmsford",
  "chemnitz",
  "chennai",
  "cherbourg",
  "chesapeake",
  "chester",
  "cheyenne",
  "chiang",
  "mai",
  "chiang",
  "rai",
  "chiavari",
  "chicago",
  "chichester",
  "chiclayo",
  "chieti",
  "chincoteague",
  "chioggia",
  "chios",
  "chișinău",
  "chokoloskee",
  "chonburi",
  "christchurch",
  "christiansted",
  "chula",
  "vista",
  "chur",
  "cincinnati",
  "ciutadella",
  "de",
  "menorca",
  "civitavecchia",
  "clarksville",
  "clearwater",
  "clearwater",
  "beach",
  "clermont-ferrand",
  "cleveland",
  "cockburn",
  "town",
  "cocoa",
  "beach",
  "coconut",
  "creek",
  "coimbra",
  "collioure",
  "colmar",
  "cologne",
  "colombo",
  "colón",
  "colonia",
  "del",
  "sacramento",
  "colorado",
  "springs",
  "columbia",
  "(south",
  "carolina)",
  "columbia",
  "(missouri)",
  "columbus",
  "como",
  "conakry",
  "concepción",
  "concord",
  "conil",
  "de",
  "la",
  "frontera",
  "conway",
  "copenhagen",
  "coral",
  "springs",
  "córdoba",
  "(argentina)",
  "córdoba",
  "(spain)",
  "corfu",
  "corinth",
  "cork",
  "coro",
  "corolla",
  "coron",
  "town",
  "coronado",
  "corpus",
  "christi",
  "corralejo",
  "cortina",
  "d'ampezzo",
  "cosenza",
  "costa",
  "adeje",
  "cotabato",
  "city",
  "cottbus",
  "courchevel",
  "courmayeur",
  "courtenay",
  "coventry",
  "covington",
  "coxen",
  "hole",
  "coyhaique",
  "cozumel",
  "crans-montana",
  "cremona",
  "crotone",
  "cruz",
  "bay",
  "cudjoe",
  "key",
  "cuenca",
  "(ecuador)",
  "cuenca",
  "(spain)",
  "cumaná",
  "cuneo",
  "cusco",
  "da",
  "nang",
  "dachau",
  "dahab",
  "dakar",
  "dallas",
  "damascus",
  "dana",
  "point",
  "dar",
  "es",
  "salaam",
  "darien",
  "darmstadt",
  "darwin",
  "daufuskie",
  "island",
  "daugavpils",
  "dauphin",
  "island",
  "davao",
  "city",
  "davenport",
  "davos",
  "dayton",
  "daytona",
  "beach",
  "deauville",
  "decatur",
  "deerfield",
  "beach",
  "del",
  "mar",
  "delft",
  "delhi",
  "delray",
  "beach",
  "den",
  "bosch",
  "denia",
  "denpasar",
  "denton",
  "denver",
  "derby",
  "derry",
  "des",
  "moines",
  "destin",
  "detroit",
  "dewees",
  "island",
  "dhaka",
  "diamond",
  "beach",
  "didim",
  "dieppe",
  "dijon",
  "dili",
  "djibouti",
  "dodoma",
  "doha",
  "dolomiti",
  "superski",
  "dordrecht",
  "dorfgastein",
  "dortmund",
  "dothan",
  "douala",
  "douglas",
  "dover",
  "(delaware)",
  "dover",
  "(new",
  "hampshire)",
  "dresden",
  "dubai",
  "dublin",
  "dubrovnik",
  "duck",
  "duisburg",
  "duluth",
  "dumaguete",
  "dumai",
  "duncan",
  "dundalk",
  "dundee",
  "dunedin",
  "dunkirk",
  "durham",
  "(uk)",
  "durham",
  "(u.s.)",
  "dushanbe",
  "düsseldorf",
  "dzaoudzi",
  "east",
  "atlantic",
  "beach",
  "east",
  "hampton",
  "eastbourne",
  "eastport",
  "eatons",
  "neck",
  "eau",
  "claire",
  "edgartown",
  "edinburgh",
  "edisto",
  "beach",
  "edmonton",
  "eilat",
  "eindhoven",
  "el",
  "nido",
  "el",
  "paso",
  "elche",
  "elizabeth",
  "elko",
  "ellmau",
  "elm",
  "emerald",
  "isle",
  "empuriabrava",
  "encinitas",
  "engelberg",
  "englewood",
  "beach",
  "enna",
  "enschede",
  "épinal",
  "erfurt",
  "erie",
  "erlangen",
  "esbjerg",
  "espace",
  "killy",
  "essaouira",
  "essen",
  "estepona",
  "étretat",
  "eugene",
  "eureka",
  "evansville",
  "everett",
  "everglades",
  "city",
  "exeter",
  "èze",
  "faenza",
  "fairbanks",
  "fakaofo",
  "falmouth",
  "famagusta",
  "fano",
  "fargo",
  "faro",
  "fayetteville",
  "(north",
  "carolina)",
  "fayetteville",
  "(arkansas)",
  "fermo",
  "fernandina",
  "beach",
  "ferrara",
  "fethiye",
  "fez",
  "fieberbrunn",
  "figure",
  "eight",
  "island",
  "filzmoos",
  "finale",
  "ligure",
  "fisher",
  "island",
  "fiumicino",
  "flagstaff",
  "flaine",
  "flint",
  "florence",
  "florence",
  "(alabama)",
  "flores",
  "foggia",
  "folgarida",
  "folly",
  "beach",
  "fontana",
  "forest",
  "beach",
  "forlì",
  "fort",
  "bragg",
  "fort",
  "caswell",
  "fort",
  "collins",
  "fort",
  "fremont",
  "fort",
  "lauderdale",
  "fort",
  "myers",
  "fort",
  "myers",
  "beach",
  "fort",
  "pierce",
  "fort",
  "smith",
  "fort",
  "walton",
  "beach",
  "fort",
  "wayne",
  "fort",
  "worth",
  "fort-de-france",
  "forte",
  "dei",
  "marmi",
  "foz",
  "do",
  "iguaçu",
  "frankfort",
  "frankfurt",
  "am",
  "main",
  "franklin",
  "frederick",
  "fredericton",
  "frederiksted",
  "freeport",
  "freetown",
  "freiburg",
  "fremont",
  "fresno",
  "fribourg",
  "fripp",
  "island",
  "frisco",
  "frogmore",
  "frosinone",
  "fuengirola",
  "fujairah",
  "fukuoka",
  "funafuti",
  "funchal",
  "gaborone",
  "gainesville",
  "galtür",
  "galway",
  "gandia",
  "garden",
  "grove",
  "garland",
  "garumaoa",
  "gastonia",
  "gatineau",
  "gaza",
  "city",
  "gdansk",
  "gdynia",
  "geelong",
  "gelsenkirchen",
  "geneva",
  "genoa",
  "george",
  "town",
  "(cayman",
  "islands)",
  "george",
  "town",
  "(malaysia)",
  "georgetown",
  "ghent",
  "gijón",
  "gilbert",
  "girona",
  "gitega",
  "giza",
  "glasgow",
  "glendale",
  "(arizona)",
  "glendale",
  "(california)",
  "gloucester",
  "gold",
  "coast",
  "goleta",
  "gorizia",
  "gosau",
  "gothenburg",
  "göttingen",
  "gouda",
  "granada",
  "(spain)",
  "granada",
  "(nicaragua)",
  "grand",
  "forks",
  "grand",
  "island",
  "(nebraska)",
  "grand",
  "island",
  "(new",
  "york)",
  "grand",
  "junction",
  "grand",
  "prairie",
  "grand",
  "rapids",
  "grande",
  "prairie",
  "granville",
  "grasse",
  "graz",
  "great",
  "falls",
  "greeley",
  "green",
  "bay",
  "greensboro",
  "greenville",
  "nc",
  "greenville",
  "sc",
  "grenoble",
  "grindelwald",
  "groningen",
  "grossarl",
  "grosseto",
  "grover",
  "beach",
  "gstaad",
  "guadalajara",
  "guadalupe",
  "guangzhou",
  "guatemala",
  "city",
  "guayaquil",
  "guelph",
  "guimarães",
  "gulf",
  "shores",
  "gulfport",
  "gustavia",
  "haarlem",
  "haifa",
  "hakahau",
  "half",
  "moon",
  "bay",
  "halifax",
  "halle",
  "hamburg",
  "hamilton",
  "(bermuda)",
  "hamilton",
  "(canada)",
  "hamilton",
  "(new",
  "zealand)",
  "hampton",
  "hampton",
  "bays",
  "hanford",
  "hangzhou",
  "hannover",
  "hanoi",
  "harare",
  "harbor",
  "island",
  "harbor",
  "isle",
  "harbour",
  "town",
  "hargeisa",
  "harkers",
  "island",
  "harrisburg",
  "hartford",
  "harvey",
  "cedars",
  "hasselt",
  "hastings",
  "hat",
  "yai",
  "hatteras",
  "hattiesburg",
  "havana",
  "healdsburg",
  "heidelberg",
  "heilbronn",
  "heiligenblut",
  "helena",
  "helsinki",
  "henderson",
  "heraklion",
  "herceg",
  "novi",
  "hereford",
  "hermosa",
  "beach",
  "hervey",
  "bay",
  "hialeah",
  "hillsboro",
  "hilton",
  "head",
  "island",
  "hilton",
  "head",
  "plantation",
  "hinterglemm",
  "hinterstoder",
  "hiroshima",
  "hitianau",
  "hoi",
  "an",
  "hobart",
  "ho",
  "chi",
  "minh",
  "city",
  "holbrook",
  "holden",
  "beach",
  "hollywood",
  "(florida)",
  "holmes",
  "beach",
  "honfleur",
  "hong",
  "kong",
  "honiara",
  "honolulu",
  "horsens",
  "hot",
  "springs",
  "houston",
  "hua",
  "hin",
  "hue",
  "hunting",
  "island",
  "huntington",
  "huntington",
  "beach",
  "huntsville",
  "hurghada",
  "hvar",
  "hyères",
  "ibiza",
  "town",
  "iloilo",
  "city",
  "imola",
  "imperia",
  "inca",
  "indian",
  "beach",
  "indianapolis",
  "ingolstadt",
  "innsbruck",
  "interlaken",
  "inverness",
  "ioannina",
  "iqaluit",
  "iquitos",
  "irvine",
  "irving",
  "ischgl",
  "isernia",
  "lahore",
  "islamorada",
  "island",
  "park",
  "isla",
  "vista",
  "isle",
  "of",
  "palms",
  "istanbul",
  "i̇zmir",
  "izola",
  "jackson",
  "jackson",
  "(tennessee)",
  "jacksonville",
  "jacksonville",
  "beach",
  "jaipur",
  "jakarta",
  "jefferson",
  "city",
  "jekyll",
  "island",
  "jena",
  "jerez",
  "de",
  "la",
  "frontera",
  "jersey",
  "city",
  "jerusalem",
  "johannesburg",
  "johns",
  "island",
  "johnson",
  "city",
  "joinville",
  "jonesboro",
  "juan",
  "griego",
  "juan-les-pins",
  "juba",
  "juiz",
  "de",
  "fora",
  "juneau",
  "jungfrau",
  "jupiter",
  "jupiter",
  "island",
  "jūrmala",
  "kabul",
  "kaiserslautern",
  "kalamata",
  "kalamazoo",
  "kamloops",
  "kampala",
  "kanchanaburi",
  "kansas",
  "city",
  "kansas",
  "city",
  "(kansas)",
  "kappl",
  "kaprun",
  "islamabad",
  "karlovy",
  "vary",
  "karlsruhe",
  "kassel",
  "kastoria",
  "kathmandu",
  "kaunas",
  "kavala",
  "kearney",
  "keene",
  "kelowna",
  "kemer",
  "kenosha",
  "key",
  "biscayne",
  "key",
  "largo",
  "key",
  "west",
  "khao",
  "lak",
  "khartoum",
  "kiawah",
  "island",
  "kiel",
  "kigali",
  "kilkenny",
  "kill",
  "devil",
  "hills",
  "kingman",
  "kingston",
  "(jamaica)",
  "kingston",
  "(norfolk",
  "island)",
  "kingston",
  "(canada)",
  "kingston",
  "upon",
  "hull",
  "kingstown",
  "kinshasa",
  "kissimmee",
  "kitchener",
  "kitty",
  "hawk",
  "kitzbühel",
  "klagenfurt",
  "klaipėda",
  "knotts",
  "island",
  "knoxville",
  "kobe",
  "koblenz",
  "kolding",
  "kolkata",
  "komotini",
  "koper",
  "korčula",
  "koror",
  "kos",
  "košice",
  "kotor",
  "krabi",
  "krakow",
  "kralendijk",
  "krefeld",
  "krk",
  "kuah",
  "kuala",
  "lumpur",
  "kure",
  "beach",
  "kuşadası",
  "kuta",
  "kutná",
  "hora",
  "kuwait",
  "city",
  "kyiv",
  "kyoto",
  "kyrenia",
  "la",
  "ceiba",
  "la",
  "ciotat",
  "la",
  "clusaz",
  "la",
  "laguna",
  "la",
  "maddalena",
  "la",
  "manga",
  "la",
  "paz",
  "la",
  "plagne",
  "la",
  "plata",
  "la",
  "rochelle",
  "la",
  "romana",
  "la",
  "serena",
  "la",
  "seyne-sur-mer",
  "la",
  "spezia",
  "la",
  "thuile",
  "laax",
  "labasa",
  "labrador",
  "city",
  "labuan",
  "bajo",
  "lady's",
  "island",
  "ladysmith",
  "lafayette",
  "(indiana)",
  "lafayette",
  "(louisiana)",
  "lagos",
  "(nigeria)",
  "lagos",
  "(portugal)",
  "laguna",
  "beach",
  "karachi",
  "lakeland",
  "lalitpur",
  "lamezia",
  "terme",
  "lancaster",
  "lancaster",
  "(u.s.)",
  "landshut",
  "lansing",
  "l'aquila",
  "laredo",
  "largo",
  "larnaca",
  "las",
  "cruces",
  "las",
  "palmas",
  "las",
  "vegas",
  "latina",
  "laurel",
  "bay",
  "lausanne",
  "lautoka",
  "laval",
  "lawton",
  "layton",
  "le",
  "havre",
  "le",
  "lavandou",
  "le",
  "mans",
  "le",
  "port",
  "le",
  "puy-en-velay",
  "lecce",
  "lecco",
  "lech",
  "leeds",
  "legian",
  "legnano",
  "leicester",
  "leiden",
  "leipzig",
  "lemgo",
  "leogang",
  "león",
  "les",
  "arcs",
  "les",
  "deux",
  "alpes",
  "les",
  "gets",
  "les",
  "houches",
  "les",
  "menuires",
  "lethbridge",
  "leuven",
  "leverkusen",
  "lexington",
  "liberec",
  "libreville",
  "lichfield",
  "lido",
  "beach",
  "lido",
  "key",
  "liège",
  "lienz",
  "liepāja",
  "lille",
  "lilongwe",
  "lima",
  "limassol",
  "limerick",
  "limoges",
  "lincoln",
  "lincoln",
  "lindos",
  "linz",
  "lisbon",
  "lisburn",
  "little",
  "rock",
  "liverpool",
  "livigno",
  "livorno",
  "ljubljana",
  "lloret",
  "de",
  "mar",
  "llucmajor",
  "loano",
  "locarno",
  "lodi",
  "lodz",
  "logan",
  "logroño",
  "lomé",
  "london",
  "(canada)",
  "london",
  "(uk)",
  "londrina",
  "long",
  "beach",
  "long",
  "beach",
  "(new",
  "york)",
  "long",
  "branch",
  "longboat",
  "key",
  "longport",
  "longview",
  "(texas)",
  "longview",
  "(washington)",
  "lorain",
  "los",
  "alamos",
  "los",
  "angeles",
  "los",
  "cabos",
  "los",
  "cristianos",
  "los",
  "gatos",
  "louisville",
  "lourdes",
  "loutraki",
  "louvain-la-neuve",
  "lowell",
  "lower",
  "grand",
  "lagoon",
  "luanda",
  "lubbock",
  "lübeck",
  "lublin",
  "lucca",
  "lucerne",
  "lugano",
  "luganville",
  "lund",
  "lusaka",
  "luxembourg",
  "luxor",
  "lyon",
  "maastricht",
  "macerata",
  "machu",
  "picchu",
  "macon",
  "madera",
  "madison",
  "madonna",
  "di",
  "campiglio",
  "madrid",
  "magaluf",
  "magdeburg",
  "mahón",
  "mainz",
  "majuro",
  "makarska",
  "malabo",
  "malaga",
  "malang",
  "maldonado",
  "malé",
  "malia",
  "malibu",
  "malmö",
  "mammoth",
  "lakes",
  "mamoudzou",
  "manacor",
  "manado",
  "managua",
  "manama",
  "manchester",
  "(uk)",
  "manchester",
  "(u.s.)",
  "máncora",
  "mandalika",
  "manhattan",
  "beach",
  "manhattan,",
  "ks",
  "manila",
  "mannheim",
  "manosque",
  "manteo",
  "mantua",
  "maputo",
  "mar",
  "del",
  "plata",
  "maracaibo",
  "marathon",
  "marbella",
  "marco",
  "island",
  "margate",
  "city",
  "maria",
  "alm",
  "maribor",
  "marigot",
  "marina",
  "del",
  "rey",
  "markham",
  "marmaris",
  "maroochydore",
  "marquette",
  "marrakesh",
  "marsa",
  "alam",
  "marsala",
  "marseille",
  "martigues",
  "masaya",
  "maseru",
  "maspalomas",
  "massa",
  "mata",
  "utu",
  "mataram",
  "matera",
  "mayrhofen",
  "mazara",
  "del",
  "vallo",
  "mbabane",
  "mckinney",
  "mechelen",
  "medan",
  "medellín",
  "medford",
  "megève",
  "melbourne",
  "(australia)",
  "melbourne",
  "(u.s.)",
  "memphis",
  "menton",
  "merano",
  "merced",
  "meribel",
  "mérida",
  "(spain)",
  "mérida",
  "(venezuela)",
  "meridian",
  "merritt",
  "island",
  "mesa",
  "messina",
  "mestre",
  "metz",
  "mexico",
  "city",
  "miami",
  "middelburg",
  "midland",
  "mijas",
  "milan",
  "milford",
  "millau",
  "milwaukee",
  "mindelo",
  "minneapolis",
  "minot",
  "minsk",
  "miquelon",
  "miramar",
  "miramar",
  "beach",
  "mishawaka",
  "mississauga",
  "missoula",
  "moab",
  "mobile",
  "modena",
  "modesto",
  "modica",
  "moena",
  "mogadishu",
  "mogi",
  "das",
  "cruzes",
  "mombasa",
  "monaco",
  "city",
  "mönchengladbach",
  "moncton",
  "monrovia",
  "(liberia)",
  "monrovia",
  "(u.s.)",
  "mons",
  "monschau",
  "montauk",
  "montecito",
  "monte",
  "carlo",
  "monte",
  "rosa",
  "montego",
  "bay",
  "montepulciano",
  "monterey",
  "montevideo",
  "montgomery",
  "montluçon",
  "montpelier",
  "montpellier",
  "montreal",
  "montreux",
  "monza",
  "moose",
  "jaw",
  "moraira",
  "moreno",
  "valley",
  "morgantown",
  "moroni",
  "morro",
  "bay",
  "morzine",
  "moscow",
  "moss",
  "landing",
  "mount",
  "vernon",
  "mountain",
  "view",
  "moutier",
  "mulhouse",
  "mumbai",
  "munich",
  "münster",
  "murcia",
  "murfreesboro",
  "murter",
  "mykonos",
  "mytilene",
  "nadi",
  "nafplio",
  "nagoya",
  "nags",
  "head",
  "nairobi",
  "namur",
  "nanaimo",
  "nancy",
  "nantes",
  "napa",
  "naples",
  "(italy)",
  "naples",
  "(u.s.)",
  "narbonne",
  "narva",
  "nashua",
  "nashville",
  "nassau",
  "navarre",
  "navarre",
  "beach",
  "naxos",
  "nazareth",
  "n'djamena",
  "negril",
  "neiafu",
  "nelson",
  "nerja",
  "netanya",
  "nevers",
  "new",
  "haven",
  "new",
  "london",
  "new",
  "orleans",
  "new",
  "smyrna",
  "beach",
  "new",
  "york",
  "city",
  "newark",
  "newcastle",
  "(australia)",
  "newcastle",
  "(uk)",
  "newport",
  "(uk)",
  "newport",
  "(rhode",
  "island)",
  "newport",
  "(vermont)",
  "newport",
  "beach",
  "newport",
  "news",
  "newry",
  "ngerulmud",
  "nha",
  "trang",
  "niagara",
  "falls",
  "(u.s.)",
  "niagara",
  "falls",
  "(canada)",
  "niamey",
  "nice",
  "nicosia",
  "nijmegen",
  "nimes",
  "niort",
  "noosa",
  "heads",
  "norfolk",
  "normal",
  "norman",
  "north",
  "captiva",
  "island",
  "north",
  "las",
  "vegas",
  "north",
  "port",
  "north",
  "topsail",
  "beach",
  "north",
  "wildwood",
  "norwalk",
  "norwich",
  "nottingham",
  "nouakchott",
  "nouméa",
  "novara",
  "novigrad",
  "nukuʻalofa",
  "nukunonu",
  "nuoro",
  "nürnberg",
  "nur-sultan",
  "nusa",
  "dua",
  "nuuk",
  "nyon",
  "oak",
  "island",
  "oakland",
  "oakville",
  "oaxaca",
  "obergurgl",
  "oberhausen",
  "ocala",
  "ocean",
  "city",
  "ocean",
  "grove",
  "ocean",
  "isle",
  "beach",
  "oceanside",
  "ocho",
  "rios",
  "ocracoke",
  "island",
  "odense",
  "odessa",
  "ogden",
  "ohomo",
  "oia",
  "okaloosa",
  "island",
  "oklahoma",
  "city",
  "olbia",
  "oldenburg",
  "olomouc",
  "olympia",
  "omaha",
  "omoa",
  "opatija",
  "orange",
  "beach",
  "oranjestad",
  "(aruba)",
  "oranjestad",
  "(sint",
  "eustatius)",
  "orem",
  "oristano",
  "orlando",
  "orléans",
  "ortisei",
  "osaka",
  "oshawa",
  "oshkosh",
  "oslo",
  "osnabrück",
  "ostrava",
  "otepa",
  "ottawa",
  "ouagadougou",
  "oulu",
  "ourense",
  "overland",
  "park",
  "oviedo",
  "owensboro",
  "oxford",
  "oxnard",
  "pacific",
  "grove",
  "padang",
  "paderborn",
  "padova",
  "pago",
  "pago",
  "pahua",
  "palanga",
  "palavas-les-flots",
  "palembang",
  "palermo",
  "palikir",
  "palm",
  "bay",
  "palm",
  "beach",
  "palm",
  "springs",
  "palma",
  "de",
  "mallorca",
  "palma",
  "nova",
  "palmetto",
  "palmetto",
  "dunes",
  "palo",
  "alto",
  "pamandzi",
  "pamplona",
  "panama",
  "city",
  "(u.s.)",
  "panama",
  "city",
  "(panama)",
  "panama",
  "city",
  "beach",
  "papeete",
  "paphos",
  "paradiski",
  "paralia",
  "paramaribo",
  "parikia",
  "paris",
  "parkersburg",
  "parksville",
  "parma",
  "pärnu",
  "parris",
  "island",
  "pasadena",
  "passo",
  "del",
  "tonale",
  "passo",
  "rolle",
  "paterson",
  "patras",
  "pattaya",
  "pau",
  "pavia",
  "pawleys",
  "island",
  "peel",
  "peguera",
  "pembroke",
  "pines",
  "peniscola",
  "pensacola",
  "pensacola",
  "beach",
  "peoria",
  "perast",
  "perdido",
  "key",
  "périgueux",
  "perpignan",
  "perros-guirec",
  "perth",
  "(australia)",
  "perth",
  "(uk)",
  "perugia",
  "pesaro",
  "pescara",
  "pescasseroli",
  "petah",
  "tikva",
  "peterborough",
  "petra",
  "petrovac",
  "pforzheim",
  "phang",
  "nga",
  "phetchabun",
  "philadelphia",
  "philipsburg",
  "phoenix",
  "phuket",
  "city",
  "piacenza",
  "pierre",
  "pine",
  "bluff",
  "pine",
  "knoll",
  "shores",
  "piraeus",
  "piran",
  "pisa",
  "pismo",
  "beach",
  "pistoia",
  "pittsburgh",
  "placencia",
  "plano",
  "playa",
  "blanca",
  "playa",
  "de",
  "las",
  "américas",
  "playa",
  "del",
  "carmen",
  "pleasure",
  "point",
  "plovdiv",
  "plymouth",
  "plzeň",
  "podgorica",
  "point",
  "lookout",
  "pointe-à-pitre",
  "poitiers",
  "pollença",
  "pompano",
  "beach",
  "pontevedra",
  "pordenone",
  "poreč",
  "porlamar",
  "port",
  "alberni",
  "port",
  "angeles",
  "port",
  "charlotte",
  "port",
  "d'andratx",
  "port",
  "louis",
  "port",
  "moresby",
  "port",
  "of",
  "spain",
  "port",
  "royal",
  "town",
  "port",
  "st.",
  "lucie",
  "port",
  "townsend",
  "port",
  "vila",
  "port-au-prince",
  "portimão",
  "portland",
  "(oregon)",
  "portland",
  "(maine)",
  "porto",
  "porto",
  "cervo",
  "porto",
  "cristo",
  "porto",
  "torres",
  "portocolom",
  "portoferraio",
  "portofino",
  "porto-novo",
  "portorož",
  "porto-vecchio",
  "portsmouth",
  "(uk)",
  "portsmouth",
  "(u.s.)",
  "portsmouth",
  "island",
  "positano",
  "potenza",
  "potsdam",
  "pouheva",
  "poznan",
  "pozzuoli",
  "prague",
  "praia",
  "praia",
  "da",
  "rocha",
  "prato",
  "prescott",
  "preston",
  "pretoria",
  "prince",
  "albert",
  "prince",
  "george",
  "prince",
  "rupert",
  "pristina",
  "propriano",
  "protaras",
  "providence",
  "provincetown",
  "provo",
  "pueblo",
  "puerto",
  "baquerizo",
  "moreno",
  "puerto",
  "cortés",
  "puerto",
  "de",
  "la",
  "cruz",
  "puerto",
  "la",
  "cruz",
  "puerto",
  "plata",
  "puerto",
  "princesa",
  "puerto",
  "rico",
  "de",
  "gran",
  "canaria",
  "puerto",
  "vallarta",
  "pula",
  "punta",
  "arenas",
  "punta",
  "cana",
  "punta",
  "del",
  "este",
  "punta",
  "gorda",
  "pyeongchang",
  "pyongyang",
  "quarteira",
  "quebec",
  "quetzaltenango",
  "quezon",
  "city",
  "quimper",
  "quito",
  "quogue",
  "rabat",
  "racine",
  "ragusa",
  "railay",
  "beach",
  "raleigh",
  "ramallah",
  "ramsey",
  "rancho",
  "cucamonga",
  "randers",
  "rapallo",
  "rapid",
  "city",
  "ras",
  "al-khaimah",
  "ras",
  "sedr",
  "ratingen",
  "ravello",
  "ravenna",
  "rayong",
  "reading",
  "red",
  "deer",
  "redding",
  "redondo",
  "beach",
  "regensburg",
  "reggio",
  "calabria",
  "reggio",
  "emilia",
  "regina",
  "rehovot",
  "reims",
  "rennes",
  "reno",
  "rethymno",
  "reus",
  "reutlingen",
  "reykjavik",
  "rhodes",
  "richmond",
  "rieti",
  "riga",
  "rijeka",
  "rikitea",
  "rimini",
  "rio",
  "de",
  "janeiro",
  "riomaggiore",
  "rishon",
  "lezion",
  "rivas",
  "riverside",
  "riviera",
  "maya",
  "road",
  "town",
  "roanoke",
  "rocamadour",
  "rochester",
  "(minnesota)",
  "rochester",
  "(new",
  "york)",
  "rock",
  "hill",
  "rockford",
  "rockville",
  "(maryland)",
  "rockville",
  "(south",
  "carolina)",
  "rodanthe",
  "rodez",
  "rogers",
  "rome",
  "ronda",
  "rosario",
  "roseau",
  "roskilde",
  "rostock",
  "roswell",
  "rotoava",
  "rotterdam",
  "roubaix",
  "rouen",
  "rovigo",
  "rovinj",
  "rutland",
  "sa",
  "coma",
  "sa",
  "pobla",
  "saalbach",
  "saarbrücken",
  "saas-fee",
  "sacramento",
  "safaga",
  "sag",
  "harbor",
  "sagaponack",
  "saguenay",
  "saint",
  "john",
  "saint",
  "paul",
  "saint",
  "petersburg",
  "saint-benoît",
  "saint-brieuc",
  "saint-denis",
  "sainte-maxime",
  "saintes-maries-de-la-mer",
  "saint-étienne",
  "saint-jean-cap-ferrat",
  "saint-jean-sur-richelieu",
  "saint-jérôme",
  "saint-joseph",
  "saint-laurent-du-maroni",
  "saint-leu",
  "saint-malo",
  "saint-paul",
  "saint-pierre",
  "(reunion)",
  "saint-pierre",
  "(saint",
  "pierre",
  "and",
  "miquelon)",
  "saint-tropez",
  "salamanca",
  "salem",
  "(oregon)",
  "salem",
  "(massachusetts)",
  "salerno",
  "salinas",
  "salisbury",
  "salou",
  "salt",
  "lake",
  "city",
  "salta",
  "salter",
  "path",
  "salvador",
  "salvo",
  "salzburg",
  "samaná",
  "san",
  "angelo",
  "san",
  "antonio",
  "san",
  "bernardino",
  "san",
  "clemente",
  "san",
  "cristóbal",
  "san",
  "diego",
  "san",
  "fernando",
  "san",
  "francisco",
  "san",
  "josé",
  "(costa",
  "rica)",
  "san",
  "jose",
  "(u.s.)",
  "san",
  "juan",
  "san",
  "juan",
  "del",
  "sur",
  "san",
  "lorenzo",
  "san",
  "luis",
  "obispo",
  "san",
  "marino",
  "san",
  "mateo",
  "san",
  "miguel",
  "san",
  "pedro",
  "san",
  "pedro",
  "de",
  "atacama",
  "san",
  "pedro",
  "sula",
  "san",
  "rafael",
  "san",
  "salvador",
  "san",
  "sebastián",
  "sanaa",
  "sandbridge",
  "sanford",
  "sanibel",
  "island",
  "sanremo",
  "sant",
  "antoni",
  "de",
  "portmany",
  "santa",
  "ana",
  "(u.s.)",
  "santa",
  "ana",
  "(el",
  "salvador)",
  "santa",
  "barbara",
  "santa",
  "clara",
  "santa",
  "clarita",
  "santa",
  "cruz",
  "santa",
  "cruz",
  "de",
  "la",
  "sierra",
  "santa",
  "cruz",
  "de",
  "tenerife",
  "santa",
  "eulària",
  "des",
  "riu",
  "santa",
  "fe",
  "santa",
  "lucía",
  "santa",
  "margherita",
  "ligure",
  "santa",
  "maria",
  "(cape",
  "verde)",
  "santa",
  "maria",
  "(u.s.)",
  "santa",
  "monica",
  "santa",
  "pola",
  "santa",
  "ponsa",
  "santa",
  "rosa",
  "santa",
  "tecla",
  "santander",
  "santanyí",
  "santiago",
  "(chile)",
  "santiago",
  "(dominican",
  "rep.)",
  "santiago",
  "de",
  "compostela",
  "santo",
  "domingo",
  "sanur",
  "sao",
  "paulo",
  "são",
  "tomé",
  "sapporo",
  "sarajevo",
  "sarasota",
  "saratoga",
  "springs",
  "s'arenal",
  "sariaya",
  "sarlat-la-canéda",
  "saskatoon",
  "sassari",
  "sault",
  "ste.",
  "marie",
  "saumur",
  "sausalito",
  "savannah",
  "savona",
  "savusavu",
  "schaffhausen",
  "schenectady",
  "schladming",
  "schwerin",
  "scottsdale",
  "scranton",
  "sea",
  "island",
  "sea",
  "isle",
  "city",
  "seabrook",
  "island",
  "seal",
  "beach",
  "seaside",
  "seattle",
  "sedona",
  "seefeld",
  "segovia",
  "semarang",
  "seminyak",
  "seoul",
  "serre",
  "chevalier",
  "sète",
  "seville",
  "shanghai",
  "sharjah",
  "sharm",
  "el-sheikh",
  "sheffield",
  "shell",
  "point",
  "shelter",
  "cove",
  "shenzhen",
  "sherbrooke",
  "shinnecock",
  "hills",
  "ship",
  "bottom",
  "shreveport",
  "šiauliai",
  "šibenik",
  "side",
  "siegen",
  "siena",
  "siesta",
  "key",
  "sineu",
  "singapore",
  "singaraja",
  "sion",
  "sioux",
  "city",
  "sioux",
  "falls",
  "sitges",
  "skiathos",
  "skopje",
  "sofia",
  "sölden",
  "söll",
  "soller",
  "solothurn",
  "sondrio",
  "sopot",
  "sorocaba",
  "sorrento",
  "south",
  "beach",
  "south",
  "bend",
  "southampton",
  "(uk)",
  "southampton",
  "(new",
  "york)",
  "southern",
  "shores",
  "split",
  "spokane",
  "springdale",
  "springfield",
  "(illinois)",
  "springfield",
  "(massachusetts)",
  "springfield",
  "(missouri)",
  "springfield",
  "(oregon)",
  "springs",
  "st",
  "albans",
  "st",
  "george's",
  "(bermuda)",
  "st",
  "pete",
  "beach",
  "st.",
  "albans",
  "st.",
  "anton",
  "st.",
  "augustine",
  "st.",
  "augustine",
  "beach",
  "st.",
  "catharines",
  "st.",
  "cloud",
  "st.",
  "gallen",
  "st.",
  "george",
  "st.",
  "george",
  "island",
  "st.",
  "george's",
  "(grenada)",
  "st.",
  "john's",
  "(antigua",
  "and",
  "barbuda)",
  "st.",
  "john's",
  "(canada)",
  "st.",
  "louis",
  "st.",
  "moritz",
  "st.",
  "petersburg",
  "(u.s.)",
  "st.",
  "simons",
  "island",
  "stamford",
  "stanley",
  "stavanger",
  "steinbach",
  "stillwater",
  "stinson",
  "beach",
  "stirling",
  "stock",
  "island",
  "stockholm",
  "stockton",
  "stoke-on-trent",
  "stone",
  "harbor",
  "strasbourg",
  "strathmere",
  "stuttgart",
  "sucre",
  "sudbury",
  "suez",
  "sukhothai",
  "sukhumi",
  "sullivan's",
  "island",
  "summerside",
  "sumter",
  "sunderland",
  "sunnyvale",
  "sunset",
  "beach",
  "sunshine",
  "coast",
  "superior",
  "surabaya",
  "surf",
  "city",
  "(new",
  "jersey)",
  "surf",
  "city",
  "(north",
  "carolina)",
  "surrey",
  "suva",
  "sveti",
  "stefan",
  "swansea",
  "sydney",
  "(australia)",
  "sydney",
  "(canada)",
  "syracuse",
  "(italy)",
  "syracuse",
  "(u.s.)",
  "szczecin",
  "taba",
  "tacloban",
  "tacoma",
  "tagbilaran",
  "taiohae",
  "taipei",
  "tallahassee",
  "tallinn",
  "tampa",
  "tampere",
  "tamworth",
  "tangier",
  "taormina",
  "taranto",
  "tarifa",
  "tarragona",
  "tartu",
  "tashkent",
  "tauplitz",
  "tauranga",
  "tavira",
  "tbilisi",
  "tegucigalpa",
  "tel",
  "aviv",
  "temecula",
  "tempe",
  "tenukupara",
  "tepukamaruia",
  "teramo",
  "ternate",
  "terni",
  "texarkana",
  "ar",
  "texarkana",
  "tx",
  "the",
  "bottom",
  "the",
  "hague",
  "the",
  "valley",
  "the",
  "wildwoods",
  "the",
  "woodlands",
  "thessaloniki",
  "thimphu",
  "thunder",
  "bay",
  "tignes",
  "tijuana",
  "tilburg",
  "timmins",
  "tinos",
  "tirana",
  "tivat",
  "tivoli",
  "tokyo",
  "toledo",
  "(spain)",
  "toledo",
  "(u.s.)",
  "tooele",
  "toowoomba",
  "topeka",
  "topsail",
  "beach",
  "toronto",
  "torre",
  "del",
  "greco",
  "torre",
  "del",
  "mar",
  "torremolinos",
  "torrevieja",
  "tórshavn",
  "toruń",
  "tossa",
  "de",
  "mar",
  "toulon",
  "toulouse",
  "tours",
  "townsville",
  "trani",
  "trapani",
  "treasure",
  "island",
  "trento",
  "trenton",
  "treviso",
  "trier",
  "trieste",
  "tripoli",
  "trogir",
  "trois-rivières",
  "tromsø",
  "trondheim",
  "trouville-sur-mer",
  "troy",
  "troyes",
  "trujillo",
  "tucson",
  "tuherahera",
  "tui",
  "tulsa",
  "tulum",
  "tupapati",
  "turin",
  "turku",
  "tuscaloosa",
  "twin",
  "falls",
  "two",
  "harbors",
  "tybee",
  "island",
  "tyler",
  "ubud",
  "udine",
  "udon",
  "thani",
  "ukiah",
  "ulaanbaatar",
  "ulcinj",
  "ulm",
  "umag",
  "upper",
  "grand",
  "lagoon",
  "uppsala",
  "urbino",
  "urubamba",
  "ushuaia",
  "utica",
  "utrecht",
  "vaduz",
  "vaitape",
  "val",
  "d’isère",
  "val",
  "di",
  "fassa",
  "val",
  "gardena",
  "val",
  "thorens",
  "valence",
  "valencia",
  "(spain)",
  "valencia",
  "(venezuela)",
  "valladolid",
  "valldemossa",
  "valle",
  "isarco",
  "vallejo",
  "valletta",
  "valparaíso",
  "vancouver",
  "(canada)",
  "vancouver",
  "(u.s.)",
  "varazze",
  "varese",
  "varna",
  "vaughan",
  "vejle",
  "venice",
  "(italy)",
  "venice",
  "(u.s.)",
  "ventimiglia",
  "ventnor",
  "city",
  "ventspils",
  "ventura",
  "verbania",
  "verbier",
  "vercelli",
  "vero",
  "beach",
  "verona",
  "versailles",
  "vevey",
  "viareggio",
  "vibo",
  "valentia",
  "viborg",
  "vicenza",
  "vichy",
  "victoria",
  "(canada)",
  "victoria",
  "(seychelles)",
  "victorville",
  "vienna",
  "vigan",
  "vigo",
  "vilamoura",
  "vilano",
  "beach",
  "villach",
  "villefranche-sur-mer",
  "vilnius",
  "viña",
  "del",
  "mar",
  "virginia",
  "beach",
  "visalia",
  "viterbo",
  "vitoria-gasteiz",
  "volos",
  "vrsar",
  "waco",
  "wainscott",
  "wakefield",
  "wanchese",
  "warsaw",
  "warth",
  "washington",
  "d.c.",
  "water",
  "mill",
  "waterford",
  "watertown",
  "watsonville",
  "waukegan",
  "waukesha",
  "waves",
  "wellington",
  "(new",
  "zealand)",
  "wellington",
  "(u.s.)",
  "wengen",
  "weno",
  "west",
  "hampton",
  "dunes",
  "west",
  "lafayette",
  "west",
  "palm",
  "beach",
  "west",
  "wildwood",
  "westendorf",
  "westhampton",
  "westhampton",
  "beach",
  "westminster",
  "weston",
  "wheeling",
  "white",
  "plains",
  "whitehorse",
  "wichita",
  "wichita",
  "falls",
  "wiesbaden",
  "wildwood",
  "wildwood",
  "crest",
  "wilkes-barre",
  "willemstad",
  "williams",
  "wilmington",
  "(delaware)",
  "wilmington",
  "(north",
  "carolina)",
  "winchester",
  "windhoek",
  "windsor",
  "winnipeg",
  "winslow",
  "winston–salem",
  "winterthur",
  "wolfsburg",
  "wollongong",
  "wolverhampton",
  "woodburn",
  "worcester",
  "(uk)",
  "worcester",
  "(u.s.)",
  "worthing",
  "wrightsville",
  "beach",
  "wroclaw",
  "wuppertal",
  "würzburg",
  "yakima",
  "yamoussoukro",
  "yaoundé",
  "yaren",
  "yellowknife",
  "yerevan",
  "yogyakarta",
  "yokohama",
  "yonkers",
  "york",
  "(uk)",
  "york",
  "(u.s.)",
  "youngstown",
  "yuma",
  "zadar",
  "zagreb",
  "zakopane",
  "zamboanga",
  "city",
  "zanzibar",
  "zaragoza",
  "zell",
  "am",
  "see",
  "zell",
  "am",
  "ziller",
  "zermatt",
  "zug",
  "zurich",
  "zwickau",
  "zwolle",
];
export const arrayOfTopics = [
  "Abortion",
  "Academics",
  "Accounting",
  "Acid Reflux",
  "ACT",
  "Activism",
  "Acupuncture",
  "Acute Lymphocytic Leukemia",
  "ADHD",
  "Addiction",
  "Adoption",
  "Advanced Placement",
  "Advertising",
  "Affirmative Action",
  "Affordable Care Act",
  "aging",
  "AIDS/ HIV",
  "Airline Credit Cards",
  "Airlines",
  "Alaska Vacations",
  "Alcohol",
  "All-Inclusive Vacations",
  "Allergic Rhinitis (hay Fever)",
  "allergies",
  "altcoin",
  "Alternative Fuels",
  "Alternative Medicine",
  "Alternative Minimum Tax",
  "Alzheimer's Disease",
  "Ambien",
  "American Health Care Act",
  "Anaphylactic Shock",
  "Animal Cruelty",
  "Animals",
  "annuities",
  "Anthrax",
  "Anthropology",
  "anti-inflammatory",
  "Antibiotics",
  "Antihistamines",
  "Antioxidants",
  "Anxiety",
  "Aortic Aneurysm",
  "Appearance",
  "Arab region universities",
  "Architecture",
  "Arizona Vacations",
  "Arrhythmia",
  "Art",
  "Arthritis",
  "Artificial Intelligence",
  "Arts And Sciences Graduate Programs",
  "Aspirin",
  "Assassinations",
  "assisted living",
  "asthma",
  "Autism",
  "Autoimmune Diseases",
  "autonomous vehicles",
  "Baby Boomers",
  "Back Problems",
  "Back To School",
  "Bacteria",
  "Bad Credit Credit Cards",
  "Bailout",
  "Balance Transfer Credit Cards",
  "Banking",
  "Bankruptcy",
  "Baseball",
  "Basketball",
  "Beach Vacations",
  "The Beatles",
  "Bees",
  "Behavior",
  "Benefits",
  "Benghazi",
  "Berlin Wall",
  "Biologic Drugs",
  "Biology",
  "biotechnology",
  "Bipolar Disorder",
  "Bird Flu",
  "Birds",
  "Birth",
  "Birth Control",
  "Birth Rate",
  "Bitcoin",
  "Black Friday",
  "BlackBerry",
  "blockchain",
  "Blogs",
  "Blood Disorders",
  "Blood Sugar",
  "Body Fat",
  "Body Image",
  "Bonds",
  "Bone Joint Health",
  "Bones",
  "Books",
  "Boston Marathon Bombing",
  "BPA",
  "Brain Cancer",
  "brain health",
  "Brain Tumor",
  "Breast Cancer",
  "Brexit",
  "Broad Prize For Urban Education",
  "Brokers",
  "Bronchitis",
  "Bronchodilators",
  "Budget Travel",
  "Bullying",
  "Business",
  "Business Credit Cards",
  "Business Growth",
  "Business School",
  "business travel",
  "C Sections",
  "Cabinet Members",
  "Caffeine",
  "Calcium",
  "California Vacations",
  "Cameras",
  "Campaign Finance",
  "Campaigns",
  "Camping Vacations",
  "Campus Health",
  "campus life",
  "Cancer",
  "Cancer Screening And Treatment",
  "Candidates",
  "capital gains",
  "capital gains taxes",
  "Capitalism",
  "Car Manufacturers",
  "Cardiology",
  "Cardiomyopathy",
  "Careers",
  "Caregiving",
  "Caribbean Vacations",
  "Cars",
  "Cash Back Credit Cards",
  "CBD",
  "Celebrities",
  "Celiac Disease",
  "Cervical Cancer",
  "Charter Schools",
  "Cheating",
  "chemical weapons",
  "Chemistry",
  "Chemotherapy",
  "Children",
  "children's health",
  "Cholesterol",
  "Christianity",
  "Christmas",
  "Chronic Lymphocytic Leukemia",
  "Circulatory Conditions",
  "Circumcision",
  "Cities",
  "Civil Rights",
  "Civil War",
  "Clinical Trials",
  "Cloning",
  "Clothing",
  "cloud stocks",
  "Coal",
  "Cocaine",
  "Cold War",
  "College Admissions",
  "College Applications",
  "College Athletics",
  "College Endowments",
  "College Majors",
  "College Search",
  "Colleges",
  "Colon Cancer",
  "Colon Health",
  "Colonoscopy",
  "Colorado Vacations",
  "Commodities",
  "Common Cold",
  "Common Core",
  "Communism",
  "Community",
  "Community Colleges",
  "Community Service",
  "Computers",
  "Concussions",
  "Congenital Heart Disease",
  "Congress",
  "Conjunctivitis",
  "Conservatives",
  "Constipation",
  "Constitution",
  "Consultants",
  "Consumers",
  "Continuing Education",
  "Convention2016",
  "Cooking",
  "COPD (chronic obstructive pulmonary disease)",
  "Copyright",
  "Coronary Artery Disease",
  "Coronavirus",
  "Company Culture",
  "Corporate Earnings",
  "Corporate Taxes",
  "Corruption",
  "Cosmetic Procedures",
  "Cosmetics",
  "Counseling",
  "Couples Vacations",
  "Courts",
  "Cover Letters",
  "CPAC",
  "Credit",
  "Credit Cards",
  "Credit Monitoring",
  "Credit Reports",
  "Credit Scores",
  "Credit Unions",
  "Crime",
  "Criminal Justice Programs",
  "Crohn's Disease",
  "Cruises",
  "Cryptocurrency",
  "CT scans",
  "Culinary School",
  "currency",
  "Customer Service",
  "Cybersecurity",
  "Cycling",
  "DACA",
  "Death",
  "Death Penalty",
  "Debates",
  "Debit Cards",
  "Debt",
  "decentralized finance",
  "Defense Spending",
  "Deficit And National Debt",
  "Deforestation",
  "Dementia",
  "Democracy",
  "Democratic National Convention",
  "Democratic Party",
  "Demographics",
  "Dental Health",
  "dentists",
  "Depression",
  "Dermatology",
  "Detainees",
  "Developing Countries",
  "diabetes",
  "Diabetes Type 1",
  "Diabetes Type 2",
  "diet and nutrition",
  "Diets",
  "Digestive Disorders",
  "Digestive Health",
  "Digital Piracy",
  "Dinosaurs",
  "Diplomacy",
  "Disability",
  "Disarmament",
  "Discrimination",
  "Diseases",
  "Disney Vacations",
  "Diversity",
  "dividends",
  "Divorce",
  "DIY",
  "Dizziness",
  "DNA tests",
  "Doctors",
  "Dogs",
  "Domestic Abuse",
  "Dow Jones Industrial Average",
  "Down Syndrome",
  "DREAM Act",
  "Driving",
  "Drones",
  "Dropout Rates",
  "Drought",
  "Drug Abuse",
  "Drugs",
  "e-commerce",
  "E. coli",
  "Ear Nose And Throat Conditions",
  "Early Childhood Education",
  "Earmarks",
  "Earth Day",
  "Earthquakes",
  "Eating Disorders",
  "Ebola",
  "Economic Austerity",
  "Economic Depression",
  "Economic Growth",
  "Economic Stimulus",
  "Economics",
  "Economy",
  "Eczema",
  "Education",
  "Education Graduate School",
  "Education Policy",
  "Education Reform",
  "Elections",
  "Electoral College",
  "electric vehicles",
  "Electricity",
  "Elementary School",
  "Email",
  "Emergency Planning",
  "Emerging Markets",
  "Emmys",
  "Employment",
  "Endangered Species",
  "Endocrinology",
  "Endometrial Cancer",
  "Energy",
  "Energy Efficiency",
  "Energy Policy And Climate Change",
  "Engineering",
  "Engineering Graduate School",
  "Enlarged Heart",
  "Entertainment",
  "Entrepreneurship",
  "Environment",
  "Epilepsy",
  "Erectile Dysfunction",
  "ESG investing",
  "Espionage",
  "Estate Taxes",
  "Estrogen",
  "Ethanol",
  "Ethereum",
  "Ethics",
  "Euro",
  "Europe Vacations",
  "Evangelicals",
  "Every Student Succeeds Act",
  "Evolution",
  "Exchange Traded Funds",
  "Executive Orders",
  "Executive Pay",
  "Executives",
  "exercise and fitness",
  "Existing Home Sales",
  "Exports",
  "Extinction",
  "Extraterrestrials",
  "Eye Health",
  "Eye Problems",
  "FAFSA",
  "Fair Credit Credit Cards",
  "Fall Vacations",
  "Family",
  "Family Health",
  "Family Vacations",
  "Farm Bill",
  "Farming",
  "Fashion",
  "Fatigue",
  "Federal Budget",
  "Federal Taxes",
  "Female Voters",
  "Feminism",
  "Fever",
  "Fibroids",
  "Fibromyalgia",
  "Financial Advisors",
  "Financial Aid",
  "Financial Goals",
  "Financial Literacy",
  "Financial Regulation",
  "fintech",
  "First Aid",
  "First Ladies",
  "FISA",
  "Fiscal Cliff",
  "Fiscal Policy",
  "Fish",
  "Flexible Spending Accounts",
  "Floods",
  "Florida Vacations",
  "Food Allergies",
  "Food And Drink",
  "Food Safety",
  "Food Stamps",
  "Food Vacations",
  "Foot Problems",
  "Football",
  "For Profit Colleges",
  "Foreclosures",
  "Foreign Aid",
  "Foreign Investment",
  "Foreign Policy",
  "Fracking",
  "Franchising",
  "Fraternities And Sororities",
  "Fraud",
  "Freebies",
  "Freedom of Information Act",
  "Freedom Of Speech",
  "Fuel Efficiency",
  "Fuel Taxes",
  "Fundraising",
  "Funds",
  "Funerals",
  "futures",
  "Gallbladder Problems",
  "Gambling",
  "Games",
  "Gardasil",
  "Gardening",
  "Gas Credit Cards",
  "Gas Prices",
  "Gastroenterology",
  "GDP",
  "Gender",
  "Gender Bias",
  "gene editing",
  "Generation X",
  "Generic Drugs",
  "Genetic Information Nondiscrimination Act",
  "Genetics",
  "Genocide",
  "Genome",
  "Gentrification",
  "Geography",
  "Geology",
  "Georgia Vacations",
  "GERD",
  "Geriatrics",
  "Gestational Diabetes",
  "Gifts",
  "Global Economy",
  "Global Universities",
  "Global Universities",
  "Global Warming",
  "Globalization",
  "Gluten",
  "GMAT",
  "Gold",
  "Golf",
  "Gout",
  "Government",
  "Government Contracts",
  "Government Intervention",
  "Government Shutdown",
  "Governors",
  "GPS",
  "Graduate Schools",
  "Graduation Rates",
  "Graves' Disease",
  "GRE",
  "Great Depression",
  "Greenhouse Gases",
  "Gun Control And Gun Rights",
  "H1N1",
  "Habits",
  "Hair Loss",
  "Hanukkah",
  "Happiness",
  "Hate Crimes",
  "Hawaii Vacations",
  "Hazing",
  "Headaches",
  "health",
  "Health Care",
  "Health Care Reform",
  "health equity",
  "Health Insurance",
  "Hearing Problems",
  "Heart Attacks",
  "heart disease",
  "Heart Failure",
  "Heart Health",
  "Heart Surgery",
  "Heart Transplants",
  "heart-healthy diet",
  "Heating",
  "Heatstroke",
  "Hedge Funds",
  "Hemochromatosis",
  "Hepatitis",
  "Heroin",
  "Hidden Fees",
  "High Blood Pressure",
  "high blood pressure diet",
  "High Credit Limits Cards",
  "High School",
  "high-fiber diet",
  "high-protein diet",
  "Hinduism",
  "Hip Replacement",
  "Hiring",
  "Hispanic Voters",
  "Hispanics",
  "Historically Black Colleges And Universities",
  "History",
  "Hockey",
  "Holiday Shopping",
  "Holidays",
  "Holocaust",
  "Home Improvements",
  "Home Insurance",
  "Home Prices",
  "Home Refinancing",
  "Home Renovations",
  "Home Repair",
  "Homeland (series)",
  "Homelessness",
  "Hormones",
  "Horses",
  "Hospitals",
  "Hotel Credit Cards",
  "Hotels and Resorts",
  "Housing",
  "Housing Market",
  "HRT",
  "Human Body",
  "Human Papillomavirus",
  "Human Rights",
  "Hunting",
  "Hurricane Harvey",
  "Hurricane Irma",
  "Hurricane Katrina",
  "Hurricane Maria",
  "Hurricane Sandy",
  "Hurricanes",
  "Hydrogen",
  "Hysterectomy",
  "Identity Theft",
  "Illinois Vacations",
  "Immigration",
  "Immigration Reform",
  "impact investing",
  "Impeachment",
  "Imports",
  "Inauguration",
  "Income",
  "Income Investing",
  "Income Tax",
  "Incontinence",
  "independent living",
  "Index Funds",
  "Indigestion",
  "Inequality",
  "Infant Mortality",
  "Infants",
  "Infections",
  "infectious diseases",
  "Infertility",
  "Inflation",
  "Influenza",
  "Infrastructure",
  "Injuries",
  "Innovation",
  "Insects",
  "Insomnia",
  "Insurance",
  "Intellectual Property",
  "Interest Rates",
  "Interior Design",
  "International Baccalaureate",
  "International Students",
  "International Trade",
  "International Treaties",
  "Internet",
  "Internships",
  "Interrogations",
  "Interviewing",
  "Investing",
  "Investing for Retirement",
  "Investing Insights",
  "invisible braces",
  "Iowa Caucus",
  "iPhone",
  "iPods",
  "IPOs",
  "Iraq War (1991)",
  "Iraq War (2003 2011)",
  "IRAs",
  "Irritable Bowel Syndrome",
  "Islam",
  "January 6th",
  "Jewelry",
  "Applying",
  "Jobs Reports",
  "Journalism",
  "Judaism",
  "Juneteenth",
  "junk bonds",
  "K 12 Education",
  "Keystone XL Pipeline",
  "Kidnapping",
  "Kidney Problems",
  "Kidney Transplants",
  "Knee Replacement",
  "Korean War",
  "Kurds",
  "Kyoto Protocol",
  "Labor",
  "Lake Vacations",
  "Landlording",
  "landscaping",
  "Languages",
  "Laptops",
  "Law",
  "Law School",
  "Lawsuits",
  "Lead Poisoning",
  "Leadership",
  "Legislation",
  "Leukemia",
  "Lgbt Rights",
  "Liberals",
  "Libor",
  "Libraries",
  "Life Insurance",
  "Liver Problems",
  "Loans",
  "Lobbying",
  "long-term care",
  "Longevity",
  "Lottery",
  "Louisiana Vacations",
  "Low Interest Credit Cards",
  "low-calorie diet",
  "LSAT",
  "Lung Cancer",
  "Lung Disease",
  "Lung Transplants",
  "Lupus",
  "Luxury",
  "Lyme Disease",
  "Macular Degeneration",
  "Magazines",
  "Malaria",
  "Mammogram",
  "Management",
  "Mantle Cell Lymphoma",
  "Manufacturing",
  "March Madness",
  "Marijuana",
  "Marketing",
  "Marriage",
  "Massage",
  "Math",
  "MBAs",
  "MCAT",
  "Measles",
  "Media",
  "Medicaid",
  "Medical Marijuana",
  "Medical Prevention",
  "Medical Quality",
  "Medical Records",
  "Medical School",
  "Medical Screening",
  "Medical Technology",
  "Medical Travel",
  "Medicare",
  "Medicine",
  "Meditation",
  "Meetings",
  "melanoma",
  "Memorial Day",
  "Memory",
  "memory care",
  "men's health",
  "Meningitis",
  "Menopause",
  "Mental Health",
  "Mergers",
  "Metabolic Syndrome",
  "Metabolism",
  "Metastatic Prostate Cancer",
  "metaverse",
  "Methodology",
  "Michigan Vacations",
  "Mid-Atlantic Vacations",
  "Middle School",
  "Mideast Peace",
  "Midwest Vacations",
  "Military",
  "Military Bases",
  "Military Courts",
  "Military Credit Cards",
  "Military Strategy",
  "Milk",
  "Millennials",
  "Minimum Wage",
  "Mining",
  "Minority Students",
  "Missiles",
  "Mobility",
  "Monetary Policy",
  "Money",
  "Money Market Funds",
  "monkeypox",
  "Montana Vacations",
  "MOOCs",
  "Mormonism",
  "Mortgages",
  "Mountain Vacations",
  "Movies",
  "Moving",
  "MRSA",
  "Multiple Sclerosis",
  "Mumps",
  "Murder",
  "Muscle Problems",
  "Music",
  "mutual funds",
  "NAFTA",
  "Nasdaq",
  "Nation",
  "National Assessment Of Educational Progress",
  "National Parks",
  "National Security",
  "National Security Terrorism And The Military",
  "Native Americans",
  "Natural Disasters",
  "Natural Gas",
  "Nephrology",
  "Net Neutrality",
  "Networking",
  "Neuroimaging",
  "Neurology",
  "Nevada Vacations",
  "New Deal",
  "New England Vacations",
  "New Hampshire Primaries",
  "New Home Sales",
  "New Jersey Vacations",
  "New Year",
  "New York Vacations",
  "Newspapers",
  "NFTs",
  "No Annual Fee Credit Cards",
  "No Balance Transfer Fees Credit Cards",
  "No Child Left Behind",
  "No Foreign Transaction Fee Credit Cards",
  "Nobel Prize",
  "Nonprofits",
  "Norovirus",
  "North Carolina Vacations",
  "NSAIDs",
  "Nuclear Power",
  "Nuclear Weapons",
  "Nurses",
  "Nursing Homes",
  "Nursing Programs",
  "Obama Administration",
  "Obama Transition",
  "Obesity",
  "Obstetrics And Gynecology",
  "Occupational Health",
  "OCD",
  "Oceans",
  "Offbeat",
  "Ohio Vacations",
  "oil",
  "The Olympics",
  "Oncology",
  "Online Education",
  "Online MBA",
  "Online Savings Accounts",
  "Ophthalmology",
  "Opioids",
  "options",
  "Oral Cancer",
  "Organic Food",
  "Osteoarthritis",
  "Osteopathy",
  "Osteoporosis",
  "Otolaryngology",
  "Outdoor Living",
  "Outsourcing",
  "Ovarian Cancer",
  "Over The Counter Drugs",
  "Pacemakers",
  "Pacific Northwest Vacations",
  "Pain Management",
  "Pancreatic Cancer",
  "Pandemic",
  "Pap Smear",
  "parent loans",
  "Parenting",
  "Paris Terror Attacks",
  "Parkinson's Disease",
  "Passports",
  "Patents",
  "Patient Advice",
  "Patient Safety",
  "Patients",
  "Paying For College",
  "Paying For Community College",
  "Paying For Graduate School",
  "pediatric cardiology",
  "Peer Pressure",
  "Pell Grants",
  "Pending Home Sales",
  "Pennsylvania Vacations",
  "Pensions",
  "performing arts",
  "personal budgets",
  "Personal Finance",
  "Pets",
  "Pharmacies",
  "Philanthropy",
  "Photo Galleries",
  "Physical Therapy",
  "Physics",
  "Pirates",
  "Plagiarism",
  "Plants",
  "Plastic",
  "Plastic Surgery",
  "Pneumonia",
  "Podcasts",
  "Police",
  "Polio",
  "Politics",
  "Polls",
  "Pollution",
  "Polygamy",
  "Population",
  "Populism",
  "Portfolio Management",
  "Poverty",
  "POWs",
  "Prediabetes",
  "Pregnancy",
  "Preschool",
  "Prescription Drugs",
  "President",
  "Presidential Pardon",
  "Presidential Speech Transcripts",
  "Prices",
  "Primaries",
  "Prison Sentences",
  "Prisons",
  "Privacy",
  "Private Schools",
  "Product Safety",
  "Productivity",
  "Products",
  "Profits",
  "Property Taxes",
  "Proposition 8",
  "Prostate",
  "Prostate Cancer",
  "Prosthetics",
  "Prostitution",
  "Protein",
  "Psoriasis",
  "Psoriatic Arthritis",
  "Psychiatry",
  "Psychology",
  "PTSD",
  "Public Health",
  "Public Schools",
  "Pulmonary Fibrosis",
  "Pulmonology",
  "Quality Of Life",
  "Quantitative Easing",
  "U.S. News Quizzes",
  "Race",
  "Racism",
  "Radiation",
  "Radiation Oncology",
  "Radio",
  "Rankings",
  "Real Estate",
  "Rebates",
  "Recalls",
  "Recession",
  "Recipes",
  "Recruiters",
  "Recycling",
  "Refugees",
  "REITs",
  "Relationships",
  "Religion",
  "Renewable Energy",
  "Renting",
  "Republican National Convention",
  "Republican Party",
  "Research",
  "Respiratory Problems",
  "Restaurants",
  "Restless Leg Syndrome",
  "Resumes",
  "Retailers",
  "Retirement",
  "Revenue",
  "Revolutionary War",
  "Rewards Credit Cards",
  "Rheumatoid Arthritis",
  "Rheumatology",
  "Rhodes Scholars",
  "Ritalin",
  "Road Trips",
  "Robots",
  "Running Mates",
  "Russia investigation",
  "Safety",
  "Salaries and Benefits",
  "Sales",
  "Sales Tax",
  "Salmonella",
  "Sarbanes Oxley Act",
  "SAT",
  "Satellites",
  "Saving For College",
  "Savings",
  "Schizophrenia",
  "Scholarships",
  "School Shootings",
  "School Vouchers",
  "Science",
  "Scoliosis",
  "Second Amendment",
  "Second Careers",
  "Secured Credit Cards",
  "Seizures",
  "semiconductors",
  "Senior Citizens",
  "Senior Health",
  "Sensory Problems",
  "sequestration",
  "Sex",
  "Sex Education",
  "Sexism",
  "Sexual Abuse",
  "sexual assault",
  "sexual health",
  "Sexual Misconduct",
  "Sexually Transmitted Diseases",
  "Shingles",
  "Shopping",
  "short squeeze",
  "Sickle Cell Disease",
  "Sign Up Bonus Credit Cards",
  "Sinusitis",
  "Skiing",
  "Skin Cancer",
  "Skin Conditions",
  "Slavery",
  "sleep",
  "Sleep Apnea",
  "Sleep Disorders",
  "Small Business",
  "Smart Cities",
  "Smartphones",
  "Smoking And Tobacco",
  "Soccer",
  "Social Anxiety Disorder",
  "Social Networking",
  "Social Security",
  "Social Security Numbers",
  "Socialism",
  "socially responsible investing",
  "Sociology",
  "Sodium",
  "Software",
  "Solar Energy",
  "Solo Vacations",
  "South Carolina Vacations",
  "Southeast Vacations",
  "Southwest Vacations",
  "Space",
  "Space Station",
  "SPDRs",
  "Special Forces",
  "Speech Problems",
  "Speeches",
  "Sports",
  "Sports Medicine",
  "spring",
  "Spring Vacations",
  "stablecoin",
  "Stafford Loans",
  "Standardized Tests",
  "Starter Cards For Building Credit",
  "Startups",
  "State Budgets",
  "State Law",
  "State Of The Union",
  "Statins",
  "Steel",
  "STEM",
  "Stem Cells",
  "STEM education",
  "STEM jobs",
  "Steroids",
  "Stock Market",
  "Stock Market News",
  "Stress",
  "Stroke",
  "Student Credit Cards",
  "student debt",
  "Student Engagement",
  "Student Loans",
  "Students",
  "Study Abroad",
  "Subprime Mortgages",
  "Sugar",
  "Suicide",
  "Summer",
  "Summer Vacations",
  "super PACs",
  "Superdelegates",
  "Supplements",
  "Surgeon General",
  "Surgery",
  "Surveys",
  "SUVs",
  "Tanning",
  "Target-Date Funds",
  "Tariffs",
  "Tax Code",
  "Tax Cuts",
  "Tax Deductions",
  "Tax Exemptions",
  "Tax Returns",
  "Taxes",
  "Tea Party",
  "Teachers",
  "Technology",
  "Teen Pregnancy",
  "Teens",
  "Telecommuting",
  "telehealth",
  "Telephones",
  "Television",
  "Temporary Employment",
  "Tennessee Vacations",
  "Tennis",
  "Terrorism",
  "Testicular Cancer",
  "Testing",
  "Testosterone",
  "Texas Vacations",
  "Textbooks",
  "Thanksgiving",
  "Theme Park Vacations",
  "Therapy",
  "Thyroid",
  "Tipping",
  "Title IX",
  "TOEFL",
  "Torture",
  "Tours",
  "Toys",
  "Trade",
  "Traffic",
  "Traffic Fatalities",
  "Trafficking",
  "Training",
  "trains",
  "Transfer Students",
  "Transgender People",
  "Transplants",
  "Transportation",
  "Travel",
  "Travel Credit Cards",
  "Travel Gear",
  "Travel Insurance",
  "Travel Rewards",
  "Travel Tips",
  "Tropical Vacations",
  "Troubled Assets Relief Program",
  "Tuberculosis",
  "Tuition",
  "U.S. Attorneys",
  "U.S. intelligence",
  "U.S. West Vacations",
  "Ulcer",
  "Ulcerative Colitis",
  "Unemployment",
  "Unions",
  "United Kingdom Vacations",
  "Unsecured Credit Cards",
  "Urban Planning",
  "US Vacations",
  "Utah Vacations",
  "Vacation Ideas",
  "Vacation Rentals",
  "Vacations",
  "Vaccines",
  "Vaping",
  "vegetarian-friendly diet",
  "Venture Capitalism",
  "Veterans",
  "Viagra",
  "Vice President",
  "Video Games",
  "Vietnam War",
  "Violence",
  "Virginia Vacations",
  "Vitamin D",
  "Vitamins",
  "Volcanoes",
  "Volunteering",
  "Voters",
  "Wages",
  "Wall Street",
  "War Crimes",
  "War In Afghanistan (2001 2014)",
  "Washington DC Vacations",
  "Washington State Vacations",
  "Water",
  "Water Park Vacations",
  "Water Safety",
  "Waterboarding",
  "Watergate",
  "Wealth",
  "Weapons",
  "Weather",
  "Websites",
  "Weekend Getaways",
  "Weight Loss",
  "West Nile Virus",
  "Whales",
  "White House",
  "Wi Fi",
  "Wildfires",
  "Wills",
  "wind power",
  "Winter Vacations",
  "Wiretapping",
  "Wisconsin Vacations",
  "Women's Colleges",
  "women's health",
  "Women's Rights",
  "Women’s History",
  "Work Life Balance",
  "Working Women",
  "World",
  "World Cup",
  "World News",
  "World War I",
  "World War II",
  "Yoga",
  "Young Professionals",
  "Young Voters",
  "Zika",
];
export const arrayOfSources = [
  "nytimes.com",
  "cnn.com",
  "foxnews.com",
  "msn.com",
  "people.com",
  "finance.yahoo.com",
  "usatoday.com",
  "news.google.com",
  "nypost.com",
  "dailymail.co.uk",
  "washingtonpost.com",
  "bbc.com",
  "news.yahoo.com",
  "cnbc.com",
  "forbes.com",
  "newsweek.com",
  "theguardian.com",
  "wsj.com",
  "apnews.com",
  "nbcnews.com",
  "cbsnews.com",
  "businessinsider.com",
  "buzzfeed.com",
  "the-sun.com",
  "the-sun.co.uk",
  "politico.com",
];
export const API_KEYS = [
  "0c03528ace2c54f1aa95824cf4c5cbfb4",
  "c0d3302a551442f96101b00eff81423",
  "96c6940895d84e5daaa58f8b9c7ac416",
  "e41cabafe8bb452d86d53ee426db0861",
  "6c4f0ed57a334072a74c6f97f2db7387",
  "db0c7fbf32804a48b0f77ef5cfd42d13",
  "18d7b7a53d1d4a73895037c6d5233fc6",
  "0ccbfc1d3b5e4b73b9546bb32cba38e1",
  "3a2af726275f4895ae195b108889261e",
  "f0d39e242b8a4c5694028c73ce16e662",
  "1df1b843d4074dc58083f8437a59b3b2",
  "8889cbf5a52245e398543f52c6d0bc6a",
  "8043ca8f1412485d8a3011796543a9be",
  "2759f5c9ecb742659e7b1ef9dcee2e9b",
  "f7c85d75d58744e8b68038cb6f4968d3",
];
